Repository ocaml-ppx/ocamlformat, pull requests merged in 2018-09, with the labels that each got.

#384 Fix: while%ext/for%ext
  src/Ast.ml
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
Labels: CLA Signed

#382 Fix: rec functor
  src/Fmt_ast.ml
  test/passing/functor.ml
Labels: CLA Signed

#385 Fix: exposed_left_typ
  src/Ast.ml
  test/passing/object.ml
Labels: CLA Signed

#389 Improve: main loop and error reporting
  src/Conf.ml
  src/Fmt_ast.ml
  src/Translation_unit.ml
  test/passing/error4.ml.ref
  test/passing/option.ml.ref
Labels: CLA Signed

#388 Fix: lazy and alias
  src/Ast.ml
  test/passing/lazy.ml
Labels: CLA Signed

#383 Fix: invalid
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/attributes.ml
  test/passing/invalid.ml
Labels: CLA Signed

#386 Fix: consecutive prefix operator
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/prefix_infix.ml
Labels: CLA Signed

#367 Improve: obey module-item-spacing for let-and bindings
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/module_item_spacing.ml
  test/passing/module_item_spacing.ml.ref
Labels: CLA Signed, Kind/Style suggestion

#394 Fix: dropped comment in revapply of extension
  src/Fmt_ast.ml
  test/passing/revapply_ext.ml
Labels: CLA Signed

#395 Fix: bad comment spacing with module-item-spacing=compact
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/module_item_spacing.ml
  test/passing/module_item_spacing.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#375 Improve: try to fit simple list/array elements on a single line
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/compact-lists-arrays.ml
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback

#390 Preset profiles (default & janestreet)
  ocamlformat-help.txt
  src/Conf.ml
  test/passing/profiles.ml
  test/passing/profiles.ml.opts
  test/passing/profiles2.ml
  test/passing/profiles2.ml.opts
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#399 Fix lost cmt near functor
  src/Fmt_ast.ml
  test/passing/comment_in_modules.ml
  test/passing/comment_in_modules.ml.ref
Labels: CLA Signed

#400 Fix: lost comment in constraint expression
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed

#381 Fix: prec of string/array sugar
  src/Ast.ml
  test/passing/source.ml.ref
  test/passing/string_array.ml
Labels: CLA Signed

#344 Improve: new option to control spacing around let bindings
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/break_cases_all.ml
  test/passing/break_cases_nested.ml
  test/passing/str_value.ml
Labels: CLA Signed

#404 Regtest: restore max-iters=2
  test/test.sh
Labels: CLA Signed

#391 Improve: disable ocamlformat if no dot ocamlformat in the project
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  test/passing/option.ml.ref
  test/passing/verbose1.ml
  test/passing/verbose1.ml.opts
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml
  test/passing/verbose2.ml.opts
  test/passing/verbose2.ml.ref
  test/test.sh
Labels: CLA Signed, Kind/To-discuss, Priority/High

#420 Fix: print error detail in debug mode only
  src/Ast.ml
  src/Fmt_ast.ml
  src/Translation_unit.ml
Labels: CLA Signed

#421 Fix: broken invariant for Pmod_unpack
  src/Ast.ml
  test/passing/module.ml
Labels: CLA Signed, Kind/Bug, Priority/Critical

#415 Improve: break after inherit
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#433 Improve: use input_name for error messages
  src/Translation_unit.ml
Labels: CLA Signed

#413 Fix doc comments
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/doc_comments.ml
  test/passing/object.ml
  test/passing/object_type.ml
Labels: CLA Signed

#437 Fix: Inconsistent spacing around comments in signatures vs structures
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/Medium

#416 Improve: support for function%ext
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
Labels: CLA Signed

#417 Fix: extension and attribute
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
Labels: CLA Signed

#414 Fix: asserts and attributes
  src/Fmt_ast.ml
  test/passing/attributes.ml
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#418 Fix: many missing comments
  src/Ast.ml
  src/Ast.mli
  src/Cmts.ml
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed

#440 Fix: corner case while formatting type variables
  src/Fmt_ast.ml
Labels: CLA Signed

#422 Fix: comment stabilization in Pexp_override
  src/Fmt_ast.ml
  test/passing/object.ml
Labels: CLA Signed, Kind/Bug, Priority/Critical

#425 Improve: explicit error message in case of 'permission denied' error
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat.ml
Labels: CLA Signed, Kind/Docs, Priority/Low

#408 Add: compact and sparse profiles
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed

#442 Test: update travis to opam 2.0.0
  .travis.yml
Labels: CLA Signed

#428 Improve: option 'cases-exp-indent' to adjust indent
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback
