Repository ocaml-ppx/ocamlformat, pull requests merged in 2018-11, with the labels that each got.

#479 Add PR test script and update contributing guidelines with expected usage
  CONTRIBUTING.md
  test/Makefile
  tools/test_branch.sh
Labels: CLA Signed

#480 Improve the formatting of lists in doc comments
  src/Fmt_odoc.ml
  test/passing/doc_comments.mli
Labels: CLA Signed

#481 Fix: Sanitize docstring check
  ocamlformat-help.txt
  src/Cmts.ml
  src/Cmts.mli
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Normalize.ml
  src/Normalize.mli
  src/Reason.ml
  src/Reason.mli
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat.ml
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#485 Improve: autocompletion of git branch names for test_branch.sh
  CONTRIBUTING.md
  tools/ocamlformat_test_branch
Labels: CLA Signed, Kind/Feature-request, Priority/Low, Status/5-Awaiting-feedback

#486 Fix: breaking of variant types
  src/Fmt_ast.ml
  test/passing/exceptions.ml
  test/passing/types.ml
Labels: CLA Signed, Kind/Bug, Priority/Low, Status/5-Awaiting-feedback

#497 fix break-struct for toplevel items (not in a struct)
  src/Fmt_ast.ml
Labels: CLA Signed

#430 Improve: option 'parens-ite'
  ocamlformat-help.txt
  src/Ast.ml
  src/Conf.ml
  src/Conf.mli
  test/passing/js_source.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low

#496 Test: improve test_branch.sh to allow different config for branch
  tools/test_branch.sh
Labels: CLA Signed

#503 Improve: formatting of or-patterns in try expressions
  src/Fmt_ast.ml
  test/passing/try_with_or_pattern.ml
Labels: CLA Signed

#510 Fix: odoc refs
  src/Fmt_odoc.ml
  test/passing/doc_comments.mli
Labels: CLA Signed, Kind/Bug, Priority/Low, Status/5-Awaiting-feedback

#509 Fix: comments should not be parsed for diff
  src/Cmts.ml
  src/Cmts.mli
  src/Normalize.ml
  src/Normalize.mli
  src/Translation_unit.ml
Labels: CLA Signed, Kind/Bug, Priority/High

#511 Fix odoc seps
  .ocamlformat
  ocamlformat-help.txt
  src/Ast.mli
  src/Conf.ml
  src/Fmt_odoc.ml
  src/Normalize.ml
  test/passing/doc_comments.mli
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High

#519 Better docstring error msgs
  src/Normalize.ml
  src/Translation_unit.ml
Labels: CLA Signed, Kind/Feature-request, Priority/Low

#520 Fix odoc normalize
  src/Fmt_odoc.ml
  src/Fmt_odoc.mli
  src/Normalize.ml
  src/Translation_unit.ml
Labels: CLA Signed, Kind/Bug, Priority/High

#518 Disable docstring parsing for external tests
  src/Cmts.ml
  test/.ocamlformat
  test/passing/.ocamlformat
  test/passing/comment_header.ml
  test/passing/comment_header.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High
