Repository ocaml-ppx/ocamlformat, pull requests merged in 2018-10, with the labels that each got.

#449 User documentation
  CONTRIBUTING.md
  README.md
Labels: CLA Signed, Kind/Docs, Priority/Low, Status/5-Awaiting-feedback

#444 Fix: outdent before arrow
  src/Fmt_ast.ml
  test/passing/break_cases_all.ml
  test/passing/break_cases_fit.ml
  test/passing/break_cases_nested.ml
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#429 Improve: option 'braces-space' to have less whitespaces
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback

#445 Read ocp indent config files
  ocamlformat-help.txt
  src/Conf.ml
  test/passing/ocp_indent_options.ml
  test/passing/ocp_indent_options.ml.opts
  test/passing/ocp_indent_options.ml.ref
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#448 Don't execute shell scripts directly in build
  src/dune
Labels: CLA Signed

#441 Fix: parens around expressions with attributes
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#452 Fix: missing parens around partially-applied `::`
  src/Fmt_ast.ml
  test/passing/custom_list.ml
Labels: CLA Signed

#402 Improve: --root option to isolate configuration files
  ocamlformat-help.txt
  ocamlformat.opam
  ocamlformat_reason.opam
  src/Conf.ml
  src/dune
  test/passing/verbose1.ml.opts
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.opts
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#453 Improve: keep a space inside tuples parens
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/High, Status/5-Awaiting-feedback

#455 Improve: set break-sequences in sparse and compact profiles
  src/Conf.ml
Labels: CLA Signed

#450 Ocamlformat diff tool
  Makefile
  README.md
  dune-project
  ocamlformat.opam
  ocamlformat_reason.opam
  tools/ocamlformat-diff/README.md
  tools/ocamlformat-diff/dune
  tools/ocamlformat-diff/ocamlformat_diff.ml
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#459 Fix exception comments
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/module_type.ml
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High

#458 Improve: record fields with attributes and docs in type definitions
  src/Fmt_ast.ml
  test/passing/attributes.ml
Labels: CLA Signed

#457 Build: a few simplifications enabled by dune 1.1.1
  Makefile
  dune
  dune-workspace.in
  ocamlformat.opam
  src/dune
Labels: CLA Signed

#466 Improve: add license header for ocamlformat_diff.ml
  tools/ocamlformat-diff/ocamlformat_diff.ml
Labels: CLA Signed

#469 Improve: shorter output of regtests
  CONTRIBUTING.md
  test/test.sh
Labels: CLA Signed, Kind/Feature-request, Priority/Low, Status/5-Awaiting-feedback

#468 Doc: disable-outside-detected-project
  README.md
  emacs/ocamlformat.el
Labels: CLA Signed, Kind/Docs, Priority/Low, Status/5-Awaiting-feedback

#460 Ocamldoc docstrings
  ocamlformat.opam
  ocamlformat_reason.opam
  src/Cmts.ml
  src/Fmt_ast.ml
  src/Fmt_odoc.ml
  src/Fmt_odoc.mli
  src/Normalize.ml
  src/dune
  src/import/Import.mli
  test/passing/doc_comments.mli
  test/passing/js_source.ml.ref
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#446 Improve: error message when docstrings move
  src/Normalize.ml
  src/Normalize.mli
  src/Reason.ml
  src/Reason.mli
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat.ml
  src/ocamlformat_reason.ml
Labels: CLA Signed, Kind/Feature-request, Priority/High, Status/5-Awaiting-feedback

#475 Fix: disable-outside-detected-project: disable ocamlformat when no .o…
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#443 Fix break struct natural
  src/Fmt_ast.ml
  src/import/Import.ml
  src/import/Import.mli
  test/passing/break_struct.ml
  test/passing/break_struct.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback
