Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-02, with the labels that each got.

#591 Add empty mli for executables
  src/ocamlformat.mli
  src/ocamlformat_reason.mli
  tools/ocamlformat-diff/ocamlformat_diff.mli
Labels: CLA Signed

#587 Improve: mishandling of field_space in record exps and patterns
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml.ref
  test/passing/exp_record.ml
  test/passing/issue85.ml
  test/passing/module_item_spacing.ml.ref
  test/passing/record_punning.ml
Labels: CLA Signed

#580 Break comment record
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml
  test/passing/comments_in_record.ml.ref
Labels: CLA Signed

#583 Break closing bracket in polymorphic variants
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/space_around_collection_expressions.ml
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#574 Implement box debugging
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  src/Translation_unit.ml
Labels: CLA Signed, Kind/Feature-request, Priority/High

#592 Make gen_version.sh use bash.
  src/dune
Labels: CLA Signed

#594 Fix 590
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat_reason.ml
Labels: CLA Signed

#595 Fix typedecl attribute
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml
  test/passing/comments_in_record.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#593 Improve: split Fmt_ast.ml
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
Labels: CLA Signed, Kind/Docs, Priority/Low, Status/5-Awaiting-feedback

#575 Remove extra space before documentation in record declarations
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/doc_comments_padding.ml
  test/passing/js_source.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#600 Fix extra break in module pack type
  src/Fmt_ast.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#601 Fix regression for variants with docstrings
  src/Fmt_ast.ml
  test/passing/types.ml
Labels: CLA Signed

#602 Fix missing break for local open record patterns
  src/Fmt_ast.ml
  test/passing/record.ml
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#604 Fix ocamlformat_reason
  Makefile
  ocamlformat_reason.opam
  src/Fmt_ast.ml
  src/Migrate_ast.ml
  src/Reason.ml
  src/Source.ml
  src/Source.mli
  src/Translation_unit.ml
  src/ocamlformat_reason.ml
  test-reason/dune
  test-reason/test-gen.ml
  test-reason/test.re
Labels: CLA Signed

#607 Fix reason wrt strings and chars
  src/Fmt_ast.ml
  test-reason/test-gen.ml
  test-reason/test.re
Labels: CLA Signed

#608 Improve reason
  Makefile
  src/Reason.ml
  src/Reason.mli
  src/ocamlformat_reason.ml
  test-reason/test-gen.ml
  test/reason/dune
  test/reason/test-gen.ml
  test/reason/test.re
Labels: CLA Signed

#606 ignore file in .ocamlformat-ignore
  Makefile
  README.md
  ocamlformat-help.txt
  src/Conf.ml
  test/Makefile
  test/disabled/dir1/.ocamlformat-ignore
  test/disabled/dir1/dir2/.ocamlformat-ignore
  test/disabled/dir1/dir2/ignore_1.ml
  test/disabled/dir1/dir2/ignore_2.ml
  test/disabled/dune
Labels: CLA Signed

#611 Do not rely on the file-system to format sources (second attempt)
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat.ml
  src/ocamlformat_reason.ml
  test/reason/test-gen.ml
  test/reason/test.re
Labels: CLA Signed

#613 Fix missing break before comment
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed

#618 include jsoo in the tests
  test/Makefile
Labels: CLA Signed

#615 Fix ignored ocamlformat attribute
  src/Cmts.ml
  src/Cmts.mli
  src/Fmt_ast.ml
  src/Translation_unit.ml
  src/Translation_unit.mli
  test/passing/wrap_comments.ml
  test/passing/wrap_comments.ml.opts
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed

#634 Fix: don't break line before wrapping comment
  src/Fmt_ast.ml
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed

#632 tools/update_tests.sh --all
  tools/update_tests.sh
Labels: CLA Signed

#631 Improve emacs setup
  README.md
Labels: CLA Signed

#636 don't include ocamlformat_diff in ocamlformat
  tools/ocamlformat-diff/dune
Labels: CLA Signed

#616 Fix type manifest formatting
  src/Fmt_ast.ml
  test/passing/break_separators.ml
  test/passing/types.ml
Labels: CLA Signed, Kind/Bug, Priority/High

#637 Fit tag-only doc comments
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/print_config.ml.ref
  test/passing/tag_only.ml
  test/passing/tag_only.mli
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion
