Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-03, with the labels that each got.

#642 Build: update to base v0.12
  ocamlformat.opam
  ocamlformat_reason.opam
  src/Cmts.ml
  src/Conf.ml
  src/Normalize.ml
Labels: CLA Signed

#648 Link to man page from readme
  README.md
Labels: CLA Signed

#654 Fix cmts in list
  src/Fmt_ast.ml
  test/passing/issue77.ml
  test/passing/js_source.ml.ref
  test/passing/list_pattern.ml
Labels: CLA Signed, Kind/Bug

#650 Fix comments on record fields
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml
  test/passing/comments_in_record.ml.ref
Labels: CLA Signed, JaneStreet

#646 Fix build on OCaml 4.06.1
  src/Reason.ml
  src/Source.ml
Labels: CLA Signed

#658 Fix: disallow '-' with other inputs
  src/Conf.ml
Labels: CLA Signed

#651 Fix cmt placement infix op
  src/Ast.ml
  src/Ast.mli
  src/Cmts.ml
  src/Fmt_ast.ml
  src/Source.ml
  src/Source.mli
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed, Kind/Bug, Priority/High

#657 Improve: check flag to check whether the input files already are formatted
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Translation_unit.ml
  src/ocamlformat.ml
  src/ocamlformat_reason.ml
Labels: CLA Signed, Kind/Feature-request

#661 Reduce the use of Poly comparisons
  src/Ast.ml
  src/Cmts.ml
  src/Fmt_odoc.ml
Labels: CLA Signed

#639 Improve: break the list of 'with type' module constraints
  src/Fmt_ast.ml
  test/passing/first_class_module.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet

#645 Add the wrap-fun-decl option
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
  test/passing/break_fun_decl-fit_or_vertical.ml
  test/passing/break_fun_decl-fit_or_vertical.ml.opts
  test/passing/break_fun_decl-fit_or_vertical.ml.ref
  test/passing/break_fun_decl-smart.ml
  test/passing/break_fun_decl-smart.ml.opts
  test/passing/break_fun_decl-smart.ml.ref
  test/passing/break_fun_decl-wrap.ml
  test/passing/break_fun_decl-wrap.ml.opts
  test/passing/break_fun_decl-wrap.ml.ref
  test/passing/break_fun_decl.ml
  test/passing/fun_decl.ml
  test/passing/js_source.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, JaneStreet

#668 Fix cmt in fun when no break infix
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
Labels: CLA Signed

#662 Fix: formatting of end line comments
  src/Fmt_ast.ml
  src/Source.ml
  src/Source.mli
  test/passing/comments.ml.opts
  test/passing/js_source.ml.ref
  test/passing/reformat_string.ml.opts
  test/passing/reformat_string.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#676 Fix constrained match in record
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/record.ml
Labels: CLA Signed

#665 Improve: fmt_module
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#677 Improve debugging output
  src/Translation_unit.ml
Labels: CLA Signed

#685 Improve: break before in for let-module construct, because of ocp-indent
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#679 Fix space around tuples
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#684 Improve: disable conf in files and attributes
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, JaneStreet

#690 Fix break before parens no wrap fun args
  src/Ast.ml
  src/Cmts.ml
  src/Conf.ml
  src/Fmt_ast.ml
  src/Translation_unit.ml
  test/passing/issue289.ml
  test/passing/wrap_comments_break.ml
  test/passing/wrap_comments_break.ml.opts
Labels: CLA Signed, JaneStreet

#689 Fix record break
  src/Fmt_ast.ml
  test/passing/break_record.ml
  test/passing/break_record.ml.opts
  test/passing/record.ml
Labels: CLA Signed, JaneStreet

#693 Fix fmt for CI
  src/Fmt_ast.ml
Labels: CLA Signed

#698 Fix incorrect ocaml code
  src/Conf.ml
  src/Fmt_ast.ml
  src/Translation_unit.ml
  test/passing/apply.ml
Labels: CLA Signed, Kind/Bug, Priority/High

#697 Fix ast changed when record ident constrained
  src/Fmt_ast.ml
  test/passing/record.ml
Labels: CLA Signed, Kind/Bug

#694 Fix value binding ocp indent compat
  src/Fmt_ast.ml
  test/passing/break_separators.ml
  test/passing/js_source.ml.ref
  test/passing/ocp_indent_compat.ml
Labels: CLA Signed, JaneStreet

#678 Fix double cmts
  src/Fmt_ast.ml
  test/passing/doc_comments.ml
  test/passing/doc_comments.mli
Labels: CLA Signed

#701 Fix empty newline before equal
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#681 Improve split attribute in let binding for expect test with uncaught exn
  src/Fmt_ast.ml
  test/passing/expect_test.ml
  test/passing/js_source.ml.ref
  test/passing/let_binding.ml
  test/passing/let_binding.ml.ref
  test/passing/module_item_spacing.ml.ref
  test/passing/option.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet

#700 Fix extra space ifthenelse
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#702 Fix js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed

#703 Add a space in "Jane Street"
  src/Conf.ml
Labels: CLA Signed

#538 Improve: module-item-spacing=preserve
  ocamlformat-help.txt
  src/Ast.ml
  src/Ast.mli
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Source.ml
  src/Source.mli
  test/passing/module_item_spacing.ml.opts
  test/passing/module_item_spacing.mli
  test/passing/module_item_spacing.mli.ref
  test/passing/module_item_spacing_compact.ml
  test/passing/module_item_spacing_compact.ml.opts
  test/passing/module_item_spacing_compact.ml.ref
  test/passing/module_item_spacing_preserve.ml
  test/passing/module_item_spacing_preserve.ml.opts
  test/passing/module_item_spacing_preserve.ml.ref
  test/passing/module_item_spacing_sparse.ml
  test/passing/module_item_spacing_sparse.ml.opts
  test/passing/module_item_spacing_sparse.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback

#710 Fix documentation of doc-comments-tag-only
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed

#705 Fix missing space before closing paren around function
  src/Fmt_ast.ml
  src/Source.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#711 Fix doc comments tag only when docstring parsing disabled
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#691 Fix infix wrap
  src/Fmt_ast.ml
  test/passing/wrap_comments.ml
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed

#714 Revert module indentation
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#663 Improve: new profiles conventional and ocamlformat
  .ocamlformat
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/.ocamlformat
  test/passing/break_cases_all.ml.ref
  test/passing/break_cases_fit.ml
  test/passing/break_cases_fit.ml.ref
  test/passing/break_cases_nested.ml.ref
  test/passing/break_cases_toplevel.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#713 Fix: parse docstrings once
  src/Fmt_ast.ml
Labels: CLA Signed

#717 Improve: put the equal first for ocp-indent-compat
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
  test/passing/ocp_indent_compat.ml
Labels: CLA Signed, JaneStreet

#715 Remove: deprecated config file syntax parsing
  src/Conf.ml
Labels: CLA Signed

#720 Improve: normalize setfield and setinstvar
  src/Fmt_ast.ml
  test/passing/field.ml
  test/passing/object.ml
Labels: CLA Signed

#725 Improve: fix associativity of Pexp_setfield
  src/Ast.ml
  test/passing/field.ml
Labels: CLA Signed

#738 Update README for new profiles
  README.md
Labels: CLA Signed

#742 Improve: comments arround attributes, fix #726
  src/Fmt_ast.ml
  test/passing/attributes.ml
Labels: CLA Signed

#743 Fix: dropped comments for pexp_record
  src/Fmt_ast.ml
  test/passing/record.ml
Labels: CLA Signed
