Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-09, with the labels that each got.

#984 Improve: allow to ignore invalid options
  ocamlformat-help.txt
  src/Conf.ml
  src/Config_option.ml
  src/Config_option.mli
  src/Parse_with_comments.ml
Labels: CLA Signed

#1002 Fix linebreak between or-cases with comments when break-cases=all
  src/Fmt_ast.ml
  test/passing/break_cases-align.ml.ref
  test/passing/break_cases-all.ml.ref
  test/passing/break_cases-closing_on_separate_line.ml.ref
  test/passing/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.ref
  test/passing/break_cases-cosl_lnmp_cmei.ml.ref
  test/passing/break_cases-fit_or_vertical.ml.ref
  test/passing/break_cases-nested.ml.ref
  test/passing/break_cases-normal_indent.ml.ref
  test/passing/break_cases-toplevel.ml.ref
  test/passing/break_cases.ml
  test/passing/break_cases.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#1007 Doc: update labels in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: CLA Signed

#1006 Fix indentation of labelled args
  src/Fmt_ast.ml
  test/passing/label_option_default_args.ml.ref
Labels: CLA Signed

#1018 Improve: don't require --name, require kind, forbid --inplace, allow --check, make --enable-outside-detected-project implicit when reading from stdin
  src/Conf.ml
  src/Conf.mli
  src/ocamlformat.ml
  src/ocamlformat_reason.ml
Labels: CLA Signed

#1013 Check functor arguments when computing placement of doc comments
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/comment_in_modules.ml.ref
  test/passing/doc_comments-after.ml.ref
  test/passing/doc_comments-before.ml.ref
  test/passing/doc_comments.ml
  test/passing/doc_comments.ml.ref
Labels: CLA Signed

#1021 Fix extra blank line in sequence
  src/Cmts.ml
  src/Cmts.mli
  src/Fmt_ast.ml
  test/passing/sequence-preserve.ml.ref
  test/passing/sequence.ml
  test/passing/sequence.ml.ref
Labels: CLA Signed

#1024 Support OCaml 4.09.0 (add the odoc.1.4.2 dependency)
  .travis.yml
  ocamlformat.opam
  ocamlformat_reason.opam
  test/passing/doc_comments.mli.ref
Labels: CLA Signed

#1023 Project: use a CHANGES.md log file again
  .travis.yml
  CHANGES.md
  tools/gen_changes.sh
Labels: CLA Signed

#1005 Improve: remove the bisect_ppx dependency and clean Makefile
  .gitignore
  Makefile
  dune
  dune-workspace.in
  ocamlformat.opam
  ocamlformat_reason.opam
  src/dune
  test-extra/Makefile
  tools/bisect.sh
  tools/test_branch.sh
Labels: CLA Signed

#1027 Fix flag of git-worktree in test_branch.sh and bisect.sh
  CHANGES.md
  tools/bisect.sh
  tools/test_branch.sh
Labels: CLA Signed

#1032 Fix test_branch.sh and CI checking of CHANGES.md
  .travis.yml
  CHANGES.md
  tools/test_branch.sh
Labels: CLA Signed

#1034 Travis: Only run CHANGES.md check on PRs
  .travis.yml
  CHANGES.md
Labels: CLA Signed

#1033 Improve: use the same sets of options for both branches by default in test_branch.sh
  CHANGES.md
  tools/test_branch.sh
Labels: CLA Signed

#1029 Fix unstable comments around attributes
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/attributes.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug :x:

#1031 Fix: no newline if the input is empty
  CHANGES.md
  src/Translation_unit.ml
  test/passing/empty.ml
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1030 Fix dropped comment after infix op
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
Labels: CLA Signed, Kind/Bug :x:
