Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-07, with the labels that each got.

#905 Improve: add the 'ocamlformat-file-kind' argument to the emacs hook
  emacs/ocamlformat.el
Labels: CLA Signed, Status/5-Awaiting-feedback

#908 Fix attribute location in Normalization
  src/Normalize.ml
  test/passing/attributes.mli
  test/passing/attributes.mli.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#909 Fix docstrings of exceptions
  src/Ast.ml
  test/passing/js_sig.mli
  test/passing/js_sig.mli.opts
  test/passing/js_sig.mli.ref
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug, Status/5-Awaiting-feedback

#913 update ocamlformat_reason opam file to 2.0 format
  ocamlformat_reason.opam
Labels: CLA Signed

#916 Fix attribute when break-infix-before-func=false
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#911 Fix monadic bindings (new 4.08 syntax)
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/monadic_binding.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#918 Fix: comments around disabled block
  src/Fmt_ast.ml
  test/passing/comments_around_disabled.ml
  test/passing/comments_around_disabled.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug

#919 Fix position of comments after anonymous functions
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed, Help-wanted, Kind/Bug, Status/5-Awaiting-feedback

#920 Improve: split the Conf.ml file
  src/Conf.ml
  src/Config_option.ml
  src/Config_option.mli
  src/dune
  src/import/Import.ml
  src/import/Import.mli
  src/import/dune
Labels: CLA Signed, Status/5-Awaiting-feedback

#928 Fix closing parenthesis indentation when on separate line
  src/Fmt_ast.ml
  test/passing/exp_grouping_preserve.ml.ref
  test/passing/js_source.ml.ref
  test/passing/sequence.ml
  test/passing/sequence.ml.ref
  test/passing/sequence_preserve.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#929 Fix break-separators=after-and-docked for record patterns
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/break_separators.ml
  test/passing/break_separators_after.ml.ref
  test/passing/break_separators_after_docked.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#930 Improve: warning 50 handled like an internal error
  src/Translation_unit.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#857 Improve: disambiguate non breaking matching structures
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  test/passing/disambiguate.ml
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#933 Improve: break with labeled arrow type
  src/Fmt_ast.ml
  test/passing/types-compact-space_around-docked.ml.ref
  test/passing/types-compact-space_around.ml.ref
  test/passing/types-compact.ml.ref
  test/passing/types-sparse-space_around.ml.ref
  test/passing/types-sparse.ml.ref
  test/passing/types.ml
  test/passing/types_indent.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#932 Improve: remove option break-string-literals
  ocamlformat-help.txt
  src/Conf.ml
  src/Config_option.ml
  src/Config_option.mli
  src/Translation_unit.ml
  test/passing/break_string_literals_never.ml.ref
  test/passing/break_string_literals_newlines.ml.ref
  test/passing/break_string_literals_newlines_and_wrap.ml.ref
  test/passing/break_string_literals_wrap.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#931 Fix break-separators=after-and-docked for lists and arrays
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/break_separators.ml
  test/passing/break_separators_after.ml.ref
  test/passing/break_separators_after_docked.ml.ref
  test/passing/compact-lists-arrays.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#935 Improve: force break after an infix op only if followed by another one
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
Labels: CLA Signed

#937 Improve: support Shell-style regular expressions in .ocamlformat-ignore and .ocamlformat-enable files
  ocamlformat-help.txt
  ocamlformat.opam
  ocamlformat_reason.opam
  src/Conf.ml
  src/dune
Labels: CLA Signed, Kind/Feature-request, Status/5-Awaiting-feedback

#946 Fix hashbang handling
  src/Translation_unit.ml
  test/passing/shebang.ml
Labels: CLA Signed

#948 Doc: enable-outside-detected-project necessary for global conf file
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, Kind/Docs, Status/5-Awaiting-feedback

#944 Doc: setting flags in .ocamlformat
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, Kind/Docs, Status/5-Awaiting-feedback

#923 Fix comments' placement (do not look at loc_stack)
  src/Cmts.ml
  test/passing/comments.ml.ref
  test/passing/label_option_default_args.ml.ref
  test/passing/loc_stack.ml.ref
  test/passing/reformat_string.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback
