Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-08, with the labels that each got.

#951 Improve: tidying up Conf.ml
  src/Conf.ml
Labels: CLA Signed

#950 Project: create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/style-suggestion.md
Labels: CLA Signed, Kind/Docs, Status/5-Awaiting-feedback

#947 Improve: new 'before' value for option 'sequence-style'
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
  test/passing/break_sequence_before.ml
  test/passing/extensions_sugar_always.ml.ref
  test/passing/kw_extentions.ml
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#952 Improve: generalize API of Config_option
  ocamlformat-help.txt
  src/Conf.ml
  src/Config_option.ml
  src/Config_option.mli
  test/passing/option.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#954 Fix: dune should not be flagged as a build dep anymore
  ocamlformat.opam
  ocamlformat_reason.opam
Labels: CLA Signed

#956 Fix: letop in subexpr
  src/Ast.ml
  test/passing/let_binding.ml
  test/passing/let_binding.ml.ref
  test/passing/let_binding_in_indent.ml.ref
  test/passing/let_binding_indent.ml.ref
Labels: CLA Signed

#963 Fix crash on record expr with pack fields
  src/Ast.ml
  test/passing/record.ml
  test/passing/record.ml.ref
  test/passing/record_loose.ml.ref
  test/passing/record_tight_decl.ml.ref
Labels: CLA Signed

#971 Fix: no box around inline odoc styles
  src/Fmt_odoc.ml
  test/passing/doc_comments.mli
  test/passing/doc_comments.mli.ref
  test/passing/js_sig.mli
  test/passing/js_sig.mli.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#973 Improve: simplify makefile
  .gitignore
  CONTRIBUTING.md
  Makefile
  dune
  dune-project
  ocamlformat.opam
  ocamlformat_diff.opam
  ocamlformat_reason.opam
  test-extra/Makefile
  test/dune
  test/failing/dune
  test/passing/dune
  test/reason/dune
  test/reason/test-gen.ml
  tools/test_branch.sh
Labels: CLA Signed

#974 API: change the type of fmt-code
  src/Cmts.ml
  src/Cmts.mli
  src/Fmt_ast.ml
  src/Fmt_odoc.ml
  src/Fmt_odoc.mli
Labels: CLA Signed, Status/5-Awaiting-feedback

#976 Fix position of comments of labelled arrow types
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
  test/passing/break_separators.ml
  test/passing/break_separators_after.ml.ref
  test/passing/break_separators_after_docked.ml.ref
  test/passing/break_separators_after_docked_wrap.ml.ref
  test/passing/break_separators_after_wrap.ml.ref
  test/passing/break_separators_wrap.ml.ref
  test/passing/ocp_indent_compat.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#975 Fix formatting of custom indexing operators
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/index_op.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#982 Improve the documentation of --doc-comments
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed

#987 Fix parens around constrained expr with attrs
  src/Fmt_ast.ml
  test/passing/attribute_and_expression.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#988 Fix: escape special characters in external declaration
  src/Fmt_ast.ml
  test/passing/string.ml
  test/passing/string.ml.ref
Labels: CLA Signed

#978 Improve: preserve begin-end keywords in if-then-else
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/exp_grouping-parens.ml.ref
  test/passing/exp_grouping.ml
  test/passing/exp_grouping.ml.ref
  test/passing/ite-compact.ml.opts
  test/passing/ite-compact.ml.ref
  test/passing/ite-compact_closing.ml.opts
  test/passing/ite-compact_closing.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#986 Fix position of expressions regarding of comments in infix-op expressions
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/comments.ml.ref
  test/passing/infix_arg_grouping.ml
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#992 Fix crash on extension sequence
  src/Fmt_ast.ml
  test/passing/extensions-indent.ml.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#996 Fix type variable
  src/Fmt_ast.ml
  test/passing/types-compact-space_around-docked.ml.ref
  test/passing/types-compact-space_around.ml.ref
  test/passing/types-compact.ml.ref
  test/passing/types-indent.ml.ref
  test/passing/types-sparse-space_around.ml.ref
  test/passing/types-sparse.ml.ref
  test/passing/types.ml
Labels: CLA Signed

#995 Fix string literal changed
  src/Fmt_ast.ml
  test/passing/break_string_literals-never.ml.ref
  test/passing/break_string_literals-newlines.ml.ref
  test/passing/break_string_literals-newlines_and_wrap.ml.ref
  test/passing/break_string_literals.ml
  test/passing/break_string_literals.ml.ref
Labels: CLA Signed

#998 Fix unstable unattached doc comment in records
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed
