Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-12, with the labels that each got.

#1172 Purify Cmts module
  lib/Cmts.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
Labels: CLA Signed, no-changelog-needed

#1173 Fix unstable cmt in or-pattern
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Params.ml
  lib/Params.mli
  test/passing/break_cases-align.ml.ref
  test/passing/break_cases-all.ml.ref
  test/passing/break_cases-closing_on_separate_line.ml.ref
  test/passing/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.ref
  test/passing/break_cases-cosl_lnmp_cmei.ml.ref
  test/passing/break_cases-fit_or_vertical.ml.ref
  test/passing/break_cases-nested.ml.ref
  test/passing/break_cases-normal_indent.ml.ref
  test/passing/break_cases-toplevel.ml.opts
  test/passing/break_cases-toplevel.ml.ref
  test/passing/break_cases.ml
  test/passing/break_cases.ml.opts
  test/passing/break_cases.ml.ref
Labels: CLA Signed

#1171 Internal: allow tests to be postprocessed with ocp-indent
  CHANGES.md
  ocamlformat.opam
  test/passing/dune.inc
  test/passing/gen/gen.ml
  test/passing/js_source.ml.ocp
  tools/travis-ci.sh
Labels: CLA Signed, JaneStreet

#1179 Remove some polymorphic comparisons
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
  lib/Normalize.ml
  lib/Sugar.ml
Labels: CLA Signed, no-changelog-needed

#1162 Refactor handling of non-formatting options
  CHANGES.md
  bin/ocamlformat.ml
  bin/ocamlformat_reason.ml
  lib/Ast.ml
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Conf.ml
  lib/Conf.mli
  lib/Fmt_ast.ml
  lib/Fmt_ast.mli
  lib/Translation_unit.ml
  lib/Translation_unit.mli
  test/cli/dune
  test/cli/max_iter_1_failing.expected
  test/cli/max_iter_1_ok.expected
Labels: CLA Signed

#1181 Extract, test and refactor Non_overlapping_interval_tree
  lib/Cmts.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
  lib/Non_overlapping_interval_tree.ml
  lib/Non_overlapping_interval_tree.mli
  ocamlformat.opam
  test/unit/dune
  test/unit/test_unit.ml
  test/unit/test_unit.mli
Labels: CLA Signed, no-changelog-needed

#1183 Remove "Internal" changelog section
  CHANGES.md
Labels: CLA Signed

#1178 Internal: clean error handling of cmdline parsing
  bin/ocamlformat.ml
  bin/ocamlformat_reason.ml
  lib/Conf.ml
  lib/Conf.mli
  lib/import/Import.ml
  lib/import/Import.mli
Labels: CLA Signed, no-changelog-needed

#1187 Remove template for style-suggestion issues
  .github/ISSUE_TEMPLATE/style-suggestion.md
Labels: CLA Signed, no-changelog-needed

#1180 Fix regression in detecting project's root
  lib/Conf.ml
  ocamlformat-help.txt
  test/projects/dune
  test/projects/outside_detected_project_with_name.expected
  test/projects/outside_detected_project_with_name/outside_root/.ocamlformat
  test/projects/outside_detected_project_with_name/outside_root/a.ml
  test/projects/outside_detected_project_with_name/outside_root/dune-project
  test/projects/outside_detected_project_with_name/project_root/.ocamlformat
  test/projects/outside_detected_project_with_name/project_root/dune-project
Labels: CLA Signed, no-changelog-needed

#1147 Improve user error messages
  CHANGES.md
  bin/ocamlformat_reason.ml
  lib/Conf.ml
  lib/Literal_lexer.mll
  lib/Reason.ml
  lib/import/Import.ml
  lib/import/Import.mli
  test/cli/conf_bad_version.expected
  test/cli/conf_malformed1.expected
  test/cli/conf_unknown_option.expected
  test/cli/conf_unknown_value.expected
  test/cli/dune
  test/cli/env_unknown_option.expected
  test/cli/env_unknown_value.expected
  test/cli/roots/bad_version/.ocamlformat
  test/cli/roots/malformed1/.ocamlformat
  test/cli/roots/unknown_option/.ocamlformat
  test/cli/roots/unknown_value/.ocamlformat
  test/passing/option.ml.ref
Labels: CLA Signed

#1190 Add copyright header to Migrate_ast.mli
  lib/Migrate_ast.mli
Labels: CLA Signed, no-changelog-needed

#1192 Add copyright header to Non_overlapping_interval_tree.ml(i)
  lib/Non_overlapping_interval_tree.ml
  lib/Non_overlapping_interval_tree.mli
Labels: CLA Signed

#1185 Remove reason support
  .gitignore
  CHANGES.md
  Makefile
  README.md
  bin/dune
  bin/ocamlformat_reason.ml
  bin/ocamlformat_reason.mli
  lib/Reason.ml
  lib/Reason.mli
  ocamlformat_reason.opam
  test-extra/Makefile
  test/reason/dune
  test/reason/test-gen.ml
  test/reason/test.re
  tools/travis-ci.sh
Labels: CLA Signed

#1189 Display standard output in the emacs plugin even when ocamlformat does not fail
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#1197 Fix opam files for running the tests in CI
  ocamlformat.opam
  ocamlformat_diff.opam
Labels: CLA Signed, no-changelog-needed

#1198 gen_version: work when building without a git root
  CHANGES.md
  tools/gen_version.mlt
Labels: CLA Signed

#1195 Format more files and pass ocaml-ci formatting step
  Makefile
  dune
  emacs/dune
  test/.ocamlformat_ignore
  test/cli/.ocamlformat
  test/cli/dune
  test/cli/dune-project
  test/disabled/dune
  test/disabled/dune-project
  test/failing/dune
  test/failing/dune-project
  test/passing/dune
  test/passing/dune-project
  test/projects/.ocamlformat
  test/projects/dune-project
  test/unit/test_unit.ml
  vendor/ocamlformat_support/dune
Labels: CLA Signed, no-changelog-needed

#1199 Constraint ocaml to 4.08 in opam file when tests are enabled
  .travis.yml
  ocamlformat.opam
  tools/travis-ci.sh
Labels: CLA Signed, no-changelog-needed
