Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-01, with the labels that each got.

#533 Preserve shebang
  src/Translation_unit.ml
  test/passing/shebang.ml
Labels: CLA Signed, Kind/Bug, Priority/Low, Status/5-Awaiting-feedback

#525 Fix formatting of types with ocp-indent-compat=true
  src/Fmt_ast.ml
  test/passing/ocp_indent_compat.ml
Labels: CLA Signed, Kind/Bug, Priority/High, Status/5-Awaiting-feedback

#461 Break separators
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/break_separators.ml
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback

#524 amend janestreet profile
  src/Conf.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed

#540 Fix suboptimal docstring formatting
  src/Fmt_odoc.ml
  test/passing/doc_comments.mli
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#463 Improve: not breaking after bind/map operators
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Priority/Low, Status/5-Awaiting-feedback

#542 Improve: some simplifications
  src/Ast.ml
  src/Fmt_ast.ml
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#546 Improve: module item spacing in sparse mode
  src/Ast.ml
  src/Cmts.ml
  src/Migrate_ast.ml
Labels: CLA Signed

#549 Fix: missing break before `; _`
  src/Ast.ml
  src/Fmt_ast.ml
Labels: CLA Signed

#551 Admin: update travis versions of ocaml and opam
  .travis.yml
Labels: CLA Signed

#552 Revise formatting of compact single case matches
  src/Ast.ml
  src/Conf.ml
  src/Fmt.ml
  src/Fmt_ast.ml
  test/passing/comments.ml.ref
  test/passing/extensions.ml.ref
  test/passing/infix_bind.ml
  test/passing/list.ml
  test/passing/match.ml
  test/passing/match2.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#565 Improve: record fields with type constraints
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml.ref
  test/passing/exp_record.ml
  test/passing/issue85.ml
Labels: CLA Signed

#567 Fix Emacs (>26.1) temporary buffer not killed
  emacs/ocamlformat.el
Labels: CLA Signed

#581 Remove global ref in Transation_unit
  src/Reason.ml
  src/Translation_unit.ml
  src/Translation_unit.mli
Labels: CLA Signed
