Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-06, with the labels that each got.

#846 Fix dropped attributes in with_constraints
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
  src/import/Import.ml
  src/import/Import.mli
  test/passing/attributes.ml
  test/passing/functor.ml
  test/passing/js_source.ml.ref
  test/passing/module_attributes.ml
  test/passing/module_type.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug, Status/5-Awaiting-feedback

#841 Improve: option max-indent
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt.ml
  src/Fmt.mli
  src/Translation_unit.ml
  test/passing/max_indent.ml
  test/passing/max_indent.ml.opts
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed, Kind/Feature-request, Status/5-Awaiting-feedback

#873 Fix unstable comment in let%ext
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#875 Enable warning 9 (based on master)
  dune-workspace.in
  src/Ast.ml
  src/Cmts.ml
  src/Conf.ml
  src/Fmt_ast.ml
  src/Migrate_ast.ml
  src/Normalize.ml
  src/Reason.ml
  src/Source.ml
  src/Sugar.ml
Labels: CLA Signed

#870 Add an option to control the indentation of nested matches
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/break_cases_normal_indent.ml
  test/passing/break_cases_normal_indent.ml.opts
  test/passing/break_cases_normal_indent.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#879 Test: break_cases_normal_indent.ml is now a symlink on break_cases_fit.ml
  test/passing/break_cases_normal_indent.ml
Labels: CLA Signed

#878 Test: extend max_indent test
  test/passing/max_indent.ml
Labels: CLA Signed

#884 Fix formatting of arguments when break-fun-decl=fit-or-vertical
  src/Fmt_ast.ml
  src/Sugar.ml
  src/Sugar.mli
  test/passing/break_fun_decl-fit_or_vertical.ml.ref
  test/passing/break_fun_decl-smart.ml.ref
  test/passing/break_fun_decl-wrap.ml.ref
  test/passing/break_fun_decl.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug, Status/5-Awaiting-feedback

#889 Fix doc comments on exceptions
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/doc_comments.after.ml.ref
  test/passing/doc_comments.before.ml.ref
  test/passing/doc_comments.ml
Labels: CLA Signed

#893 Format gen_version.ml
  HACKING.org
  Makefile
  ocamlformat.opam
  ocamlformat_reason.opam
  src/dune
  test/Makefile
  tools/gen_version.mlt
Labels: CLA Signed

#886 Improve: Implement break-fun-sig without Location.is_single_line
  src/Fmt_ast.ml
  test/passing/break_fun_decl-fit_or_vertical.ml.opts
  test/passing/break_fun_decl-fit_or_vertical.ml.ref
  test/passing/break_fun_decl-smart.ml.opts
  test/passing/break_fun_decl-smart.ml.ref
  test/passing/break_fun_decl-wrap.ml.opts
  test/passing/break_fun_decl-wrap.ml.ref
  test/passing/break_fun_decl.ml
  test/passing/js_source.ml.ref
  test/passing/ocp_indent_compat.ml
Labels: CLA Signed

#887 Fix break-string-literals=newlines
  src/Fmt_ast.ml
  test/passing/break_string_literals_never.ml
  test/passing/break_string_literals_never.ml.opts
  test/passing/break_string_literals_never.ml.ref
  test/passing/break_string_literals_newlines.ml
  test/passing/break_string_literals_newlines.ml.opts
  test/passing/break_string_literals_newlines.ml.ref
  test/passing/break_string_literals_wrap.ml
  test/passing/break_string_literals_wrap.ml.opts
  test/passing/break_string_literals_wrap.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#892 Improve: option break-before-in
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/break_before_in_auto.ml
  test/passing/break_before_in_auto.ml.opts
  test/passing/break_before_in_auto.ml.ref
  test/passing/break_before_in_fit_or_vertical.ml
  test/passing/break_before_in_fit_or_vertical.ml.opts
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#894 Improve: specify break hint in fits_breaks
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  src/Params.ml
Labels: CLA Signed

#885 Improve: synchronize Format with upstream stdlib
  src/Fmt.ml
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed

#828 Improve: option exp-grouping
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/exp_grouping_parens.ml
  test/passing/exp_grouping_parens.ml.opts
  test/passing/exp_grouping_parens.ml.ref
  test/passing/exp_grouping_preserve.ml
  test/passing/exp_grouping_preserve.ml.opts
  test/passing/exp_grouping_preserve.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#883 Improve: align cases horizontally
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  test/passing/align_cases.ml
  test/passing/align_cases.ml.opts
  test/passing/align_cases_break_all.ml
  test/passing/align_cases_break_all.ml.opts
  test/passing/align_cases_break_all.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed, Kind/Feature-request, Status/5-Awaiting-feedback

#856 Fix inconsistency of break-separators=after-and-docked for record expressions
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/break_separators.ml
  test/passing/break_separators.ml.opts
  test/passing/break_separators_after.ml
  test/passing/break_separators_after.ml.opts
  test/passing/break_separators_after.ml.ref
  test/passing/break_separators_after_docked.ml
  test/passing/break_separators_after_docked.ml.opts
  test/passing/break_separators_after_docked.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#898 Fix compilation with 4.06 and 4.07
  vendor/ocamlformat_support/compat/ge_408.ml
  vendor/ocamlformat_support/compat/lt_408.ml
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed, Kind/Bug

#899 Improve: add trailing semicolon inside record when break-separators=after-and-docked
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  src/ocamlformat_reason.ml
  test/passing/break_separators.ml
  test/passing/break_separators_after.ml.ref
  test/passing/break_separators_after_docked.ml.ref
  test/passing/js_source.ml.ref
  test/passing/types-compact-space_around-docked.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#881 Improve: dunify testsuite
  ocamlformat.opam
  ocamlformat_reason.opam
  test/Makefile
  test/failing/dune
  test/failing/list_and_comments.ml.broken-ref
  test/passing/align_infix.ml.opts
  test/passing/break_cases_align.ml.opts
  test/passing/break_record.ml.opts
  test/passing/cmdline_override.ml.opts
  test/passing/cmdline_override2.ml.opts
  test/passing/dune
  test/passing/error1.ml.ref
  test/passing/error2.ml.ref
  test/passing/error3.ml.ref
  test/passing/error4.ml.ref
  test/passing/extensions_indent.ml.opts
  test/passing/extensions_indent.mli.opts
  test/passing/extensions_sugar_always.ml.opts
  test/passing/function_indent_always.ml.opts
  test/passing/function_indent_never.ml.opts
  test/passing/infix_precedence.ml.opts
  test/passing/ite.ml.opts
  test/passing/ite_fit_or_vertical.ml.opts
  test/passing/ite_fit_or_vertical_no_indicate.ml.opts
  test/passing/ite_kr.ml.opts
  test/passing/ite_kw_first.ml.opts
  test/passing/ite_kw_first_no_indicate.ml.opts
  test/passing/ite_no_indicate.ml.opts
  test/passing/js_source.ml.opts
  test/passing/list-space_around.ml.opts
  test/passing/match_indent_always.ml.opts
  test/passing/match_indent_never.ml.opts
  test/passing/module_item_spacing_compact.ml.opts
  test/passing/module_item_spacing_preserve.ml.opts
  test/passing/module_item_spacing_sparse.ml.opts
  test/passing/need_format.ml.opts
  test/passing/need_format.ml.ref
  test/passing/option.ml.ref
  test/passing/print_config.ml.deps
  test/passing/print_config.ml.opts
  test/passing/print_config.ml.ref
  test/passing/profiles.ml.opts
  test/passing/tuple.ml.opts
  test/passing/tuple_less_parens.ml.opts
  test/passing/types-compact-space_around-docked.ml.opts
  test/passing/types-compact-space_around.ml.opts
  test/passing/types-sparse-space_around.ml.opts
  test/passing/verbose1.ml.opts
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.opts
  test/passing/verbose2.ml.ref
  test/passing/wrap_comments_break.ml.opts
  test/test.sh
  tools/update_tests.sh
Labels: CLA Signed
