Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-04, with the labels that each got.

#740 Improve: support --name with --inplace
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed

#752 Fix grammar: it's -> its
  src/Conf.ml
Labels: CLA Signed

#735 Fix module pack and functor
  src/Fmt_ast.ml
  src/import/Import.ml
  src/import/Import.mli
  test/passing/first_class_module.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet

#756 Fix: update ocamlformat-help.txt (follow up on #752)
  ocamlformat-help.txt
Labels: CLA Signed

#764 Small cleanup
  src/Ast.ml
  src/Migrate_ast.ml
  src/Reason.ml
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed

#716 Fix module type functor
  src/Fmt_ast.ml
  test/passing/functor.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#763 Support for OCaml 4.08
  Makefile
  src/Cmts.ml
  src/Fmt_ast.ml
  src/Translation_unit.ml
  src/compat/ge_408.ml
  src/compat/lt_408.ml
  src/dune
  tools/gen_compat.ml
  vendor/ocamlformat_support/compat/ge_408.ml
  vendor/ocamlformat_support/compat/lt_408.ml
  vendor/ocamlformat_support/config/gen.ml
  vendor/ocamlformat_support/dune
  vendor/ocamlformat_support/format_.ml
Labels: CLA Signed

#759 Fix non-wrapping asterisk prefixed cmts
  src/Cmts.ml
  test/passing/wrap_comments.ml
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#760 Fix nested parens with no break infix before func
  src/Fmt_ast.ml
  test/passing/match2.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#748 Tidying fmt ast
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
Labels: CLA Signed, Priority/Low, Status/5-Awaiting-feedback

#773 Fix indentation of functor argument
  src/Fmt_ast.ml
  test/passing/functor.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#755 Fix inconsistent break before module signature
  src/Fmt_ast.ml
  test/passing/break_struct.ml.ref
  test/passing/js_source.ml.ref
  test/passing/module.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#739 Unecessary breaks in module pack
  src/Fmt_ast.ml
  test/passing/first_class_module.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#762 Improve: less breaks for break-cases=all but correctly breaks or-patterns
  src/Conf.ml
  src/Fmt_ast.ml
  src/Params.ml
  test/passing/break_cases_all.ml.ref
  test/passing/break_cases_fit.ml
  test/passing/break_cases_fit.ml.ref
  test/passing/break_cases_nested.ml.ref
  test/passing/break_cases_toplevel.ml.ref
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Style suggestion, Status/5-Awaiting-feedback

#774 Fix: --use-file/--impl/--intf should override file extension
  src/Conf.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#758 Fix: if $HOME/.config is either not set or empty, a default equal…
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#751 Fix weird parens break
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#761 Improve: --disable-outside-detected-project is set by default
  README.md
  emacs/ocamlformat.el
  ocamlformat-help.txt
  src/Conf.ml
  test/passing/print_config.ml.opts
  test/passing/verbose2.ml.opts
Labels: CLA Signed, Status/5-Awaiting-feedback

#768 Improve: new option let-module
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/let_module_compact.ml
  test/passing/let_module_compact.ml.opts
  test/passing/let_module_compact.ml.ref
  test/passing/let_module_sparse.ml
  test/passing/let_module_sparse.ml.opts
  test/passing/let_module_sparse.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Style suggestion, Status/5-Awaiting-feedback

#775 Fix missing space before attribute on includes
  src/Cmts.ml
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#767 Improve: less sensitivity to concrete syntax
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#779 fix minor issue with handling certain edge cases
  src/Fmt_ast.ml
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
Labels: CLA Signed

#784 Improve: Fmt.noop
  src/Cmts.ml
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  src/Fmt_odoc.ml
  src/Params.ml
Labels: CLA Signed

#782 Fix: type extension
  src/Fmt_ast.ml
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
  test/passing/extensions.mli
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#781 Break after anonymous function arrow after infix op
  src/Fmt_ast.ml
  test/passing/infix_bind.ml
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#786 Fix: functor application and break-struct wrap incorrectly
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/let_module_compact.ml.ref
  test/passing/let_module_sparse.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#785 Improve: new option break-fun-sig
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#787 Improve: K&R style for if-then-else
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Params.ml
  src/Params.mli
  test/passing/ite_kr.ml
  test/passing/ite_kr.ml.opts
  test/passing/ite_kr.ml.ref
  test/passing/option.ml.ref
Labels: CLA Signed

#802 Fix colon break module type functor
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/module_type.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#797 Improve: break with type constraints
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#806 Remove dead link to preset profiles
  README.md
Labels: CLA Signed

#804 Fix: comment in empty structure
  src/Fmt_ast.ml
  test/passing/module.ml
Labels: CLA Signed, JaneStreet, Kind/Bug, Status/5-Awaiting-feedback

#808 Improve: tidying Fmt_ast
  src/Fmt_ast.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#810 Improve: break-cases-all shouldn't break nested patterns
  src/Fmt_ast.ml
  test/passing/break_cases_all.ml.ref
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#811 Improve: change formatting of newtypes
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/ocp_indent_compat.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#809 Fix let module sparse
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/let_module_compact.ml
  test/passing/let_module_compact.ml.ref
  test/passing/let_module_sparse.ml.ref
Labels: CLA Signed, JaneStreet, Kind/Bug, Status/5-Awaiting-feedback

#803 Improve: better consistency between structures and signatures
  src/Fmt_ast.ml
  test/passing/js_source.ml.ref
  test/passing/recmod.mli
  test/passing/source.ml.ref
  test/passing/tag_only.mli
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback
