Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-05, with the labels that each got.

#801 Fix break before ending paren
  src/Ast.ml
  src/Cmts.ml
  src/Conf.ml
  src/Fmt.ml
  src/Fmt_ast.ml
  src/Migrate_ast.ml
  src/Normalize.ml
  src/Params.ml
  src/Reason.ml
  src/Source.ml
  src/Translation_unit.ml
  src/ocamlformat.ml
  test/passing/extensions.ml.ref
  test/passing/extensions_sugar_always.ml.ref
  test/passing/fun_decl.ml
  test/passing/infix_arg_grouping.ml
  test/passing/issue289.ml
  test/passing/ite.ml
  test/passing/ite_fit_or_vertical.ml.ref
  test/passing/ite_kr.ml.ref
  test/passing/ite_kw_first.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#812 Improve: preserve record type annot
  src/Fmt_ast.ml
  src/Source.ml
  src/Source.mli
  test/passing/comments_in_record.ml
  test/passing/comments_in_record.ml.ref
  test/passing/record.ml
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#815 Improve: preserve the position of type annotation in bindings
  src/Fmt_ast.ml
  test/passing/comments.ml.ref
  test/passing/extensions.ml.ref
  test/passing/extensions_sugar_always.ml.ref
  test/passing/js_source.ml.ref
  test/passing/let_binding.ml
  test/passing/let_binding.ml.ref
  test/passing/module.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#818 Improve: remove break before ending paren for anonymous functions
  src/Ast.ml
  src/Cmts.ml
  src/Conf.ml
  src/Fmt.ml
  src/Fmt_ast.ml
  src/Params.ml
  src/Reason.ml
  src/Source.ml
  src/Sugar.ml
  src/Translation_unit.ml
  test/passing/infix_arg_grouping.ml
  test/passing/issue289.ml
  test/passing/js_source.ml.ref
  test/passing/object.ml
  test/passing/source.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#819 Improve: space before type constraint in record
  ocamlformat-help.txt
  src/Conf.ml
  src/Fmt_ast.ml
  test/passing/comments_in_record.ml.ref
  test/passing/record.ml
  test/passing/record.ml.opts
  test/passing/record_loose.ml
  test/passing/record_loose.ml.opts
  test/passing/record_loose.ml.ref
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#821 Improve: tidying Fmt_ast.ml
  src/Fmt_ast.ml
Labels: CLA Signed

#814 Improve: preserve blank lines in sequences
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/print_config.ml.ref
  test/passing/sequence.ml
  test/passing/sequence.ml.opts
  test/passing/sequence.ml.ref
  test/passing/sequence_preserve.ml
  test/passing/sequence_preserve.ml.opts
  test/passing/sequence_preserve.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#826 Fix: performance issue with long list literals
  src/Cmts.ml
  src/Migrate_ast.ml
Labels: CLA Signed

#822 Improve: options 'let-binding-indent', 'type-decl-indent' and 'indent-after-in'
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/let_binding_in_indent.ml
  test/passing/let_binding_in_indent.ml.opts
  test/passing/let_binding_in_indent.ml.ref
  test/passing/let_binding_indent.ml
  test/passing/let_binding_indent.ml.opts
  test/passing/let_binding_indent.ml.ref
  test/passing/print_config.ml.ref
  test/passing/types_indent.ml
  test/passing/types_indent.ml.opts
  test/passing/types_indent.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Feature-request, Status/5-Awaiting-feedback

#823 Improve: make Sugar.list_exp and Sugar.list_pat tail-recursive
  src/Sugar.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#832 Fix exception when calling String.sub
  src/Source.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#833 Further improve speed with ofday_unit_tests_v1.ml
  src/Ast.ml
Labels: CLA Signed

#836 Improve: don't fit tag-only comments after val declarations
  src/Ast.ml
  src/Ast.mli
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
  test/passing/tag_only.mli
Labels: CLA Signed, JaneStreet

#838 Improve: preserve blank lines in conventional and sparse profiles
  src/Conf.ml
Labels: CLA Signed, Status/5-Awaiting-feedback

#837 Improve: finer space-around-exp options
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Params.ml
  test/passing/exp_record.ml
  test/passing/list-space_around.ml.opts
  test/passing/list-space_around.ml.ref
  test/passing/list.ml
  test/passing/print_config.ml.ref
  test/passing/types-compact-space_around-docked.ml.opts
  test/passing/types-compact-space_around.ml.opts
  test/passing/types-sparse-space_around.ml.opts
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Status/5-Awaiting-feedback

#847 Fix pro position for with_constraints
  src/Fmt_ast.ml
  test/passing/module.ml
Labels: CLA Signed, JaneStreet, Status/5-Awaiting-feedback

#852 Fix vim instructions
  README.md
Labels: CLA Signed

#859 Fix: rename sexp_list into list
  src/Sugar.mli
Labels: CLA Signed

#860 Clean: Cleanup usage of Poly
  src/Cmts.ml
  src/Conf.ml
  src/Fmt_ast.ml
  src/Fmt_odoc.ml
  src/Migrate_ast.ml
  src/Normalize.ml
Labels: CLA Signed

#861 Cleanup cmts.ml
  src/Cmts.ml
Labels: CLA Signed

#858 Fix: test.sh
  test/test.sh
Labels: CLA Signed

#862 clean Hashtbl.Poly
  src/Ast.ml
  src/Cmts.ml
Labels: CLA Signed

#864 Check that all locations have been considered during formatting
  src/Cmts.ml
  src/Cmts.mli
  src/Translation_unit.ml
Labels: CLA Signed

#854 Improve: .ocamlformat-enable files listing files to format when ocamlformat is disabled by default
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed, Kind/Feature-request, Status/5-Awaiting-feedback

#853 Improve: new options to support 'with' and 'strict_with' (ocp-indent)
  ocamlformat-help.txt
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/function_indent_always.ml
  test/passing/function_indent_always.ml.opts
  test/passing/function_indent_always.ml.ref
  test/passing/function_indent_never.ml
  test/passing/function_indent_never.ml.opts
  test/passing/function_indent_never.ml.ref
  test/passing/let_binding_indent.ml.ref
  test/passing/match_indent_always.ml
  test/passing/match_indent_always.ml.opts
  test/passing/match_indent_always.ml.ref
  test/passing/match_indent_never.ml
  test/passing/match_indent_never.ml.opts
  test/passing/match_indent_never.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed, Kind/Style suggestion, Status/5-Awaiting-feedback

#855 Fix inconsistency of break-separators for wildcards in match cases
  src/Fmt_ast.ml
  test/passing/break_separators.ml
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback

#866 Fix dropped comments in list patterns and module types
  src/Fmt_ast.ml
  test/passing/comments.ml
  test/passing/comments.ml.opts
  test/passing/comments.ml.ref
  test/passing/js_source.ml.ref
  test/passing/label_option_default_args.ml.ref
  test/passing/module_type.ml
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug, Status/5-Awaiting-feedback
