Repository ocaml-ppx/ocamlformat, pull requests merged in 2019-10, with the labels that each got.

#1039 Fix indexing operators precedence
  CHANGES.md
  src/Ast.ml
  src/Fmt_ast.ml
  test/passing/index_op.ml
Labels: CLA Signed

#1036 CI: check the build with OCaml 4.07.1 and 4.08.0
  .travis.yml
  CHANGES.md
  test/passing/dune
Labels: CLA Signed

#1045 Fix blank line after comments at the end of lists
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/issue77.ml
Labels: CLA Signed

#1046 Fix alignment of cases
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/align_cases-break_all.ml.ref
  test/passing/align_cases.ml
Labels: CLA Signed

#1044 CI: use opam-2.0.5 in Travis
  .travis.yml
  CHANGES.md
Labels: CLA Signed

#1051 Fix: add missing cut before attributes in type declarations
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/margin_80.ml
  test/passing/margin_80.ml.opts
  test/passing/margin_80.ml.ref
Labels: CLA Signed

#1050 Improve: inline extensions that do not break
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/doc_comments-after.ml.ref
  test/passing/doc_comments-before.ml.ref
  test/passing/doc_comments.ml.ref
  test/passing/extensions-indent.ml.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#1052 Fix placement of doc comments around extensions
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/doc_comments-after.ml.ref
  test/passing/doc_comments-before.ml.ref
  test/passing/doc_comments.ml.ref
Labels: CLA Signed

#1054 Fix newlines and indentation in toplevel extension points
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/extensions-indent.ml.ref
  test/passing/extensions-indent.mli.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/extensions.ml
  test/passing/extensions.ml.ref
  test/passing/extensions.mli
  test/passing/js_source.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed, Kind/Bug :x:

#1059 Improve: remove utility functions from Fmt_ast
  CHANGES.md
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  src/Migrate_ast.ml
  src/Params.ml
  src/Params.mli
Labels: CLA Signed

#1057 Improve: auto mode for break-string-literals instead of {wrap,newlines,newlines-and-wrap}
  CHANGES.md
  ocamlformat-help.txt
  src/Ast.ml
  src/Conf.ml
  src/Conf.mli
  src/Fmt_ast.ml
  test/passing/break_string_literals-never.ml.ref
  test/passing/break_string_literals-newlines.ml.opts
  test/passing/break_string_literals-newlines.ml.ref
  test/passing/break_string_literals-newlines_and_wrap.ml.opts
  test/passing/break_string_literals-newlines_and_wrap.ml.ref
  test/passing/break_string_literals.ml.opts
  test/passing/break_string_literals.ml.ref
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1062 Improve: allow both values of boolean options
  CHANGES.md
  ocamlformat-help.txt
  src/Conf.ml
  src/Config_option.ml
Labels: CLA Signed

#1063 CI: use a script travis-ci.sh to simplify .travis.yml
  .travis.yml
  CHANGES.md
  tools/travis-ci.sh
Labels: CLA Signed

#1058 Fix precedence of Dot wrt Hash
  CHANGES.md
  src/Ast.ml
  src/Ast.mli
  test/passing/index_op.ml
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#1060 Improve: set conventional as the default profile
  CHANGES.md
  README.md
  ocamlformat-help.txt
  src/Conf.ml
Labels: CLA Signed

#1075 Improve and cleanup sequence_blank_line (fix empty_line_between)
  CHANGES.md
  src/Ast.ml
  src/Cmts.ml
  src/Fmt_ast.ml
  src/Params.ml
  src/Source.ml
  src/Source.mli
  test/passing/module_item_spacing-preserve.ml.ref
  test/passing/sequence-preserve.ml.opts
  test/passing/sequence-preserve.ml.ref
  test/passing/sequence.ml
  test/passing/sequence.ml.opts
  test/passing/sequence.ml.ref
Labels: CLA Signed

#1077 Improve: implement sequence-blank-line=preserve-one for let bindings
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/sequence-preserve.ml.ref
  test/passing/sequence.ml
  test/passing/sequence.ml.ref
Labels: CLA Signed

#1073 Fix break before the closing bracket of collections (exceeding the margin)
  CHANGES.md
  src/Params.ml
  test/passing/break_record.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed

#1079 CI: factorize tests and check reason build
  CHANGES.md
  tools/travis-ci.sh
Labels: CLA Signed

#1082 Tests: do not use ocaml syntax in the dune file
  CHANGES.md
  test/passing/.ocamlformat
  test/passing/dune
  test/passing/dune.inc
  test/passing/gen/dune
  test/passing/gen/gen.ml
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1078 Internal: clean Translation_unit
  CHANGES.md
  src/Translation_unit.ml
  src/Translation_unit.mli
  src/ocamlformat.ml
  src/ocamlformat_reason.ml
Labels: CLA Signed

#1083 API: optional names for formatting boxes
  CHANGES.md
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
Labels: CLA Signed

#1089 Internal: add an API to parse removed configuration values
  CHANGES.md
  src/Conf.ml
  src/Config_option.ml
  src/Config_option.mli
  test/passing/break_separators-after_docked_transition_message.ml.opts
  test/passing/break_separators-after_docked_transition_message.ml.ref
  test/passing/break_separators-after_docked_transition_message.ml.should-fail
  test/passing/break_string_literals-wrap.ml.opts
  test/passing/break_string_literals-wrap.ml.ref
  test/passing/break_string_literals-wrap.ml.should-fail
  test/passing/dune.inc
Labels: CLA Signed, Kind/Feature-request

#1096 Fix closing quote exceeding the margin
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
Labels: CLA Signed

#1103 Fix: missing break before attributes of Pmty_with
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/attributes.ml
  test/passing/module_attributes.ml.ref
Labels: CLA Signed

#1098 Fix closing parenthesis exceeding the margin in function application
  CHANGES.md
  src/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ref
  test/passing/margin_80.ml
  test/passing/margin_80.ml.ref
Labels: CLA Signed

#1105 Fix the default value documentation for max-indent
  CHANGES.md
  ocamlformat-help.txt
  src/Conf.ml
  src/Config_option.ml
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1106 Internal: Future-proof Fmt API in case Fmt.t goes abstract
  CHANGES.md
  src/Cmts.ml
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  src/Fmt_odoc.ml
  src/Translation_unit.ml
  src/import/Import.ml
  src/import/Import.mli
Labels: CLA Signed

#1111 Improve: give a hint when warning 50 is raised
  CHANGES.md
  src/Translation_unit.ml
  test/passing/error3.ml.ref
Labels: CLA Signed

#1109 Internal: Make Fmt.t abstract
  CHANGES.md
  src/Cmts.ml
  src/Fmt.ml
  src/Fmt.mli
  src/Fmt_ast.ml
  src/Translation_unit.ml
Labels: CLA Signed
