Repository ocaml-ppx/ocamlformat, pull requests merged in 2020-12, with the labels that each got.

#1558 Add tests about comments inside attributes
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed, no-changelog-needed

#1559 Update recommended version (0.16.0) in README
  README.md
Labels: CLA Signed, no-changelog-needed

#1556 Fix comments on the same line as prev and next elements
  CHANGES.md
  lib/Cmts.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/source.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#1555 Break or-patterns after comments and preserve their position at the end of line
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/break_cases-align.ml.ref
  test/passing/break_cases-all.ml.ref
  test/passing/break_cases-closing_on_separate_line.ml.ref
  test/passing/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.ref
  test/passing/break_cases-cosl_lnmp_cmei.ml.ref
  test/passing/break_cases-fit_or_vertical.ml.ref
  test/passing/break_cases-nested.ml.ref
  test/passing/break_cases-normal_indent.ml.ref
  test/passing/break_cases-toplevel.ml.ref
  test/passing/break_cases.ml.ref
  test/passing/comment_in_empty.ml
Labels: CLA Signed

#1557 ocamlformat.el: add buffer filename in logs
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#1560 Fix linebreak between signature items of the same group
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
Labels: CLA Signed

#1566 Add a unit test for `Fmt.list_pn`
  test/unit/test_fmt.ml
Labels: CLA Signed, no-changelog-needed

#1563 Remove the deprecated 'let-open' option
  CHANGES.md
  lib/Conf.ml
  lib/Conf.mli
  lib/Fmt_ast.ml
  ocamlformat-help.txt
  test/cli/removed_option.t
  test/passing/dune.inc
  test/passing/open-auto.ml.minimum-ocaml-version
  test/passing/open-auto.ml.opts
  test/passing/open-auto.ml.ref
  test/passing/open-long.ml.minimum-ocaml-version
  test/passing/open-long.ml.opts
  test/passing/open-long.ml.ref
  test/passing/open-preserve.ml.minimum-ocaml-version
  test/passing/open-preserve.ml.opts
  test/passing/open-preserve.ml.ref
  test/passing/open-short.ml.minimum-ocaml-version
  test/passing/open-short.ml.opts
  test/passing/open-short.ml.ref
  test/passing/print_config.ml.opts
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1568 Add Fmt.sequence as a generalization for ($)
  lib/Fmt.ml
  lib/Fmt.mli
  test/unit/test_fmt.ml
Labels: CLA Signed, no-changelog-needed

#1562 Fix stack overflow on large string constants
  CHANGES.md
  lib/Fmt.ml
  test/cli/large_string.t
Labels: CLA Signed

#1571 Update build status shield for ocaml-ci
  README.md
Labels: CLA Signed, no-changelog-needed

#1572 Remove part of comment that is causing merlin to report an error, masking the real errors
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed

#1573 Add missing deps required for parse-wyc (for the linter of the CI)
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no-changelog-needed

#1549 Bump minimal ocaml version requirement to 4.08
  CHANGES.md
  dune-project
  lib/Fmt_ast.ml
  lib/Source.ml
  lib/Source.mli
  ocamlformat.opam
  test/failing/dune.inc
  test/failing/indent_empty.ml.minimum-ocaml-version
  test/failing/js_functor.ml.minimum-ocaml-version
  test/failing/module.ml.minimum-ocaml-version
  test/failing/nesting.ml.minimum-ocaml-version
  test/failing/never_align.ml.minimum-ocaml-version
  test/failing/unit_classes.ml.minimum-ocaml-version
  test/failing/unit_extensions.ml.minimum-ocaml-version
  test/failing/unit_lex.ml.minimum-ocaml-version
  test/failing/unit_modtypes.ml.minimum-ocaml-version
  test/failing/unit_values.ml.minimum-ocaml-version
  test/passing/attributes.ml.minimum-ocaml-version
  test/passing/comments.ml.minimum-ocaml-version
  test/passing/comments_in_record.ml.minimum-ocaml-version
  test/passing/directives.mlt.minimum-ocaml-version
  test/passing/doc_comments-after.ml.minimum-ocaml-version
  test/passing/doc_comments-before-except-val.ml.minimum-ocaml-version
  test/passing/doc_comments-before.ml.minimum-ocaml-version
  test/passing/doc_comments.ml.minimum-ocaml-version
  test/passing/doc_comments.mli.minimum-ocaml-version
  test/passing/dune.inc
  test/passing/extensions-indent.ml.minimum-ocaml-version
  test/passing/extensions-sugar_always.ml.minimum-ocaml-version
  test/passing/extensions.ml.minimum-ocaml-version
  test/passing/infix_bind-break.ml.minimum-ocaml-version
  test/passing/infix_bind-fit_or_vertical-break.ml.minimum-ocaml-version
  test/passing/infix_bind-fit_or_vertical.ml.minimum-ocaml-version
  test/passing/infix_bind.ml.minimum-ocaml-version
  test/passing/invalid_docstring.ml.minimum-ocaml-version
  test/passing/js_source.ml.minimum-ocaml-version
  test/passing/let_binding-in_indent.ml.minimum-ocaml-version
  test/passing/let_binding-indent.ml.minimum-ocaml-version
  test/passing/let_binding.ml.minimum-ocaml-version
  test/passing/match2.ml.minimum-ocaml-version
  test/passing/module_item_spacing.mli.minimum-ocaml-version
  test/passing/monadic_binding.ml.minimum-ocaml-version
  test/passing/open.ml.minimum-ocaml-version
  test/passing/sequence-preserve.ml.minimum-ocaml-version
  test/passing/sequence.ml.minimum-ocaml-version
  test/passing/source.ml.minimum-ocaml-version
  test/passing/types-compact-space_around-docked.ml.minimum-ocaml-version
  test/passing/types-compact-space_around.ml.minimum-ocaml-version
  test/passing/types-compact.ml.minimum-ocaml-version
  test/passing/types-indent.ml.minimum-ocaml-version
  test/passing/types-sparse-space_around.ml.minimum-ocaml-version
  test/passing/types-sparse.ml.minimum-ocaml-version
  test/passing/types.ml.minimum-ocaml-version
  vendor/compat/gen/gen.ml
  vendor/compat/warning/lt_408.ml
  vendor/token-latest/406/token_latest.ml
  vendor/token-latest/detect/detect.ml
Labels: CLA Signed

#1547 Use tokens_between instead of string_between
  lib/Cmts.ml
  lib/Source.mli
Labels: CLA Signed, no-changelog-needed

#1567 Fix comment position around list cons operator
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/list-space_around.ml.ref
  test/passing/list.ml
Labels: CLA Signed, Kind/To-discuss

#1570 Clean up formatting of match/try expressions
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed
