Repository ocaml-ppx/ocamlformat, pull requests merged in 2020-05, with the labels that each got.

#1358 Merge doc-comments-val with doc-comments, new value before-except-val; after becomes after-when-possible
  CHANGES.md
  lib/Conf.ml
  lib/Conf.mli
  lib/Fmt_ast.ml
  ocamlformat-help.txt
  test/passing/doc_comments-after.ml.opts
  test/passing/doc_comments-before-except-val.ml.minimum-ocaml-version
  test/passing/doc_comments-before-except-val.ml.opts
  test/passing/doc_comments-before-except-val.ml.ref
  test/passing/doc_comments-before.ml.opts
  test/passing/doc_comments-val-after.ml.opts
  test/passing/dune.inc
  test/passing/print_config.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1362 0.14.2 release
  CHANGES.md
Labels: CLA Signed

#1346 Do not break odoc inline elements
  CHANGES.md
  lib/Fmt_odoc.ml
  test/passing/doc_comments.mli
  test/passing/doc_comments.mli.ref
  test/passing/js_sig.mli.ref
Labels: CLA Signed

#1350 Do not clear the emacs *compilation* buffer on successful reformat
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#1322 Fix disabling with attributes on < 4.08
  CHANGES.md
  lib/Source.ml
  test/passing/dune.inc
  test/passing/skip.ml.minimum-ocaml-version
Labels: CLA Signed

#1196 Port to dune 2.0
  dune
  test/.ocamlformat_ignore
  test/cli/dune
  test/cli/dune-project
  test/disabled/dune
  test/disabled/dune-project
  test/failing/dune
  test/failing/dune-project
  test/passing/dune
  test/passing/dune-project
  test/passing/dune.inc
  test/passing/gen/gen.ml
  test/projects/dune
  test/projects/dune-project
Labels: CLA Signed, no-changelog-needed

#1342 Restore previous functionality for pre-post extension points
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/pre_post_extensions.ml
Labels: CLA Signed

#1343 Fix extra break before function body of fun
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Source.ml
  test/passing/dune.inc
  test/passing/fun_function.ml
  test/passing/max_indent.ml
Labels: CLA Signed

#1352 Preserve unwrapped comments
  CHANGES.md
  lib/Cmt.ml
  lib/Cmt.mli
  lib/Cmts.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/wrap_comments.ml
  test/passing/wrap_comments.ml.ref
Labels: CLA Signed, JaneStreet

#1367 Break long literal strings at the margin
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/js_source.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
Labels: CLA Signed

#1384 Update recommended version in the README
  README.md
Labels: CLA Signed, Kind/Docs, no-changelog-needed
