Repository ocaml-ppx/ocamlformat, pull requests merged in 2020-06, with the labels that each got.

#1386 Update opam metadata
  ocamlformat.opam
Labels: CLA Signed, no-changelog-needed

#1378 Externalize Prec, Assoc and better precedence ambiguity type
  lib/Assoc.ml
  lib/Assoc.mli
  lib/Ast.ml
  lib/Ast.mli
  lib/Prec.ml
  lib/Prec.mli
  lib/Sugar.ml
  lib/Sugar.mli
Labels: CLA Signed, no-changelog-needed

#1376 Distinguish hash-getter from hash-comparison infix operators
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  test/passing/source.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#1360 Break after a multiline argument in an argument list
  CHANGES.md
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Fmt_ast.ml
  test/passing/args_grouped.ml
  test/passing/args_grouped.ml.opts
  test/passing/dune.inc
  test/passing/js_source.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
Labels: CLA Signed

#1381 Type constraint on return type of anonymous functions is now always printed before the function body
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/fun_decl.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#1383 Fix placement of comments on constants
  CHANGES.md
  lib/Cmts.ml
  lib/Fmt_ast.ml
  lib/Source.ml
  lib/Source.mli
  test/passing/loc_stack.ml.ref
  test/passing/reformat_string.ml.ref
Labels: CLA Signed

#1393 Correctly capitalize OCaml in the README
  README.md
Labels: no-changelog-needed

#1392 Build on OCaml 4.11+alpha3
  lib/Fmt_ast.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
  lib/Source.ml
  lib/dune
  lib/token-latest/406/token_latest.ml
  lib/token-latest/408/token_latest.ml
  lib/token-latest/411/token_latest.ml
  lib/token-latest/README.md
  lib/token-latest/detect/detect.ml
  lib/token-latest/detect/detect.mli
  lib/token-latest/detect/dune
  lib/token-latest/dune
Labels: CLA Signed, no-changelog-needed

#1391 Do not escape @raise argument in docstrings
  CHANGES.md
  lib/Fmt_odoc.ml
  test/passing/doc_comments.mli
  test/passing/doc_comments.mli.ref
Labels: CLA Signed

#1395 Move token_latest library to vendor directory
  vendor/token-latest/406/token_latest.ml
  vendor/token-latest/408/token_latest.ml
  vendor/token-latest/411/token_latest.ml
  vendor/token-latest/README.md
  vendor/token-latest/detect/detect.ml
  vendor/token-latest/detect/detect.mli
  vendor/token-latest/detect/dune
  vendor/token-latest/dune
Labels: CLA Signed, no-changelog-needed

#1372 Fix missing open line between multi-line let-binding with poly-typexpr
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/let_binding_spacing-double-semicolon.ml.opts
  test/passing/let_binding_spacing-double-semicolon.ml.ref
  test/passing/let_binding_spacing-sparse.ml.opts
  test/passing/let_binding_spacing-sparse.ml.ref
  test/passing/let_binding_spacing.ml
  test/passing/let_binding_spacing.ml.opts
Labels: CLA Signed

#1397 Put type annotation of function return type before definition
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/comments.ml.ref
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#1382 Remove trailing space after expression when followed by an attribute and break before attributes attached to multi-line phrases
  CHANGES.md
  lib/Fmt.ml
  lib/Fmt.mli
  lib/Fmt_ast.ml
  test/passing/assignment_operator-op_begin_line.ml.ref
  test/passing/assignment_operator.ml.ref
  test/passing/attributes.ml
  test/passing/break_separators-after.ml.ref
  test/passing/break_separators-after_docked.ml.ref
  test/passing/break_separators-after_docked_wrap.ml.ref
  test/passing/break_separators-after_wrap.ml.ref
  test/passing/break_separators-before_docked.ml.ref
  test/passing/break_separators-before_docked_wrap.ml.ref
  test/passing/break_separators-wrap.ml.ref
  test/passing/break_separators.ml
  test/passing/compact_lists_arrays.ml
  test/passing/extensions-indent.ml.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/extensions.ml.ref
  test/passing/field-op_begin_line.ml.ref
  test/passing/field.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/let_module-sparse.ml.ref
  test/passing/let_module.ml.ref
  test/passing/module_attributes.ml.ref
  test/passing/shortcut_ext_attr.ml
  test/passing/source.ml.ref
Labels: CLA Signed
