Repository ocaml-ppx/ocamlformat, pull requests merged in 2020-03, with the labels that each got.

#1272 Only skip tests that require 4.08.0
  ocamlformat.opam
  test/passing/attributes.ml.minimum-ocaml-version
  test/passing/comments.ml.minimum-ocaml-version
  test/passing/comments_in_record.ml.minimum-ocaml-version
  test/passing/directives.mlt.minimum-ocaml-version
  test/passing/doc_comments-after.ml.minimum-ocaml-version
  test/passing/doc_comments-before.ml.minimum-ocaml-version
  test/passing/doc_comments-val-after.ml.minimum-ocaml-version
  test/passing/doc_comments.ml.minimum-ocaml-version
  test/passing/doc_comments.mli.minimum-ocaml-version
  test/passing/dune.inc
  test/passing/extensions-indent.ml.minimum-ocaml-version
  test/passing/extensions-sugar_always.ml.minimum-ocaml-version
  test/passing/extensions.ml.minimum-ocaml-version
  test/passing/gen/gen.ml
  test/passing/infix_bind-break.ml.minimum-ocaml-version
  test/passing/infix_bind-fit_or_vertical-break.ml.minimum-ocaml-version
  test/passing/infix_bind-fit_or_vertical.ml.minimum-ocaml-version
  test/passing/infix_bind.ml.minimum-ocaml-version
  test/passing/js_source.ml.minimum-ocaml-version
  test/passing/let_binding-in_indent.ml.minimum-ocaml-version
  test/passing/let_binding-indent.ml.minimum-ocaml-version
  test/passing/let_binding.ml.minimum-ocaml-version
  test/passing/match2.ml.minimum-ocaml-version
  test/passing/module_item_spacing.mli.minimum-ocaml-version
  test/passing/monadic_binding.ml.minimum-ocaml-version
  test/passing/open-auto.ml.minimum-ocaml-version
  test/passing/open-long.ml.minimum-ocaml-version
  test/passing/open-preserve.ml.minimum-ocaml-version
  test/passing/open-short.ml.minimum-ocaml-version
  test/passing/open.ml.minimum-ocaml-version
  test/passing/sequence-preserve.ml.minimum-ocaml-version
  test/passing/sequence.ml.minimum-ocaml-version
  test/passing/skip.ml.minimum-ocaml-version
  test/passing/source.ml.minimum-ocaml-version
  test/passing/types-compact-space_around-docked.ml.minimum-ocaml-version
  test/passing/types-compact-space_around.ml.minimum-ocaml-version
  test/passing/types-compact.ml.minimum-ocaml-version
  test/passing/types-indent.ml.minimum-ocaml-version
  test/passing/types-sparse-space_around.ml.minimum-ocaml-version
  test/passing/types-sparse.ml.minimum-ocaml-version
  test/passing/types.ml.minimum-ocaml-version
Labels: CLA Signed

#1270 Remove suppression of warning 28
  lib/Translation_unit.ml
Labels: CLA Signed, no-changelog-needed

#1277 Support multi-indices extended indexing operators
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  lib/Params.ml
  lib/Params.mli
  test/passing/dune.inc
  test/passing/multi_index_op.ml
  test/passing/multi_index_op.ml.minimum-ocaml-version
Labels: CLA Signed

#1279 Support multi indices extended indexing operators
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  lib/Params.mli
  test/passing/index_op.ml
  test/passing/multi_index_op.ml
  test/unit/test_ast.ml
  test/unit/test_ast.mli
  test/unit/test_unit.ml
Labels: CLA Signed

#1280 Unecessary parens in indexing operators
  CHANGES.md
  lib/Ast.ml
  test/passing/index_op.ml
Labels: CLA Signed

#1276 Handle OCaml 4.10.0 AST
  CHANGES.md
  lib/Ast.ml
  lib/Fmt_ast.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
  lib/Source.ml
  lib/Sugar.ml
  lib/Sugar.mli
  ocamlformat.opam
  test/passing/comment_in_modules.ml.ref
  test/passing/comments.ml
  test/passing/comments.ml.ref
  test/passing/dune.inc
  test/passing/module_anonymous.ml
  test/passing/module_anonymous.ml.minimum-ocaml-version
Labels: CLA Signed

#1292 Remove redundant field ignores
  lib/Ast.ml
  lib/Fmt_ast.ml
Labels: no-changelog-needed

#1302 Fix bad rebase between #1296 and #1299
  test/passing/protected_object_types.ml
Labels: no-changelog-needed

#1304 Surround indexing operators lhs when it's an integer
  CHANGES.md
  lib/Ast.ml
  test/passing/index_op.ml
Labels: CLA Signed

#1311 Preserve empty doc-comments syntax
  CHANGES.md
  lib/Cmt.ml
  lib/Source.ml
  lib/Source.mli
  test/passing/doc_comments.mli
  test/passing/doc_comments.mli.ref
Labels: CLA Signed

#1290 Fix formatting of comment with just a newline
  CHANGES.md
  lib/Cmt.ml
  lib/Fmt.ml
  lib/Fmt.mli
  test/passing/comments.ml
  test/passing/comments.ml.ref
Labels: CLA Signed

#1309 Fix dropped comment in module unpack
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/first_class_module.ml
Labels: CLA Signed

#1289 Handle lazy patterns as arguments to class
  CHANGES.md
  lib/Ast.ml
  test/passing/object.ml
Labels: CLA Signed

#1303 Preserve cinaps comments containing code
  CHANGES.md
  lib/Cmt.ml
  test/passing/cinaps.ml
Labels: CLA Signed

#1312 Preserve functor syntax for consistency
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Source.ml
  lib/Source.mli
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
Labels: CLA Signed

#1314 Fix normalization of attributes, fixing the docstrings in attributes
  CHANGES.md
  lib/Normalize.ml
  test/passing/attributes.ml
Labels: CLA Signed

#1317 Add missing parentheses around OR-patterns with attributes
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/attributes.ml
Labels: CLA Signed

#1316 Fix spacing inside parens for symbols when the spacing was handled by the englobing exp
  CHANGES.md
  lib/Ast.ml
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
  test/passing/source.ml.ref
  test/passing/symbol.ml
Labels: CLA Signed

#1293 Deprecate some options before 0.14
  CHANGES.md
  lib/Conf.ml
  lib/Config_option.ml
  lib/Config_option.mli
  ocamlformat-help.txt
  test/passing/doc_comments-after.ml.ref
  test/passing/doc_comments-before.ml.ref
  test/passing/doc_comments-val-after.ml.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/verbose1.ml.ref
  test/passing/verbose2.ml.ref
Labels: CLA Signed

#1320 Extract fmt_elements_collection
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed

#1319 Refactor Cmts (followup for #1172)
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed

#1315 Fix invalid (unparsable) docstrings
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/invalid_docstring.ml
  test/passing/invalid_docstring.ml.minimum-ocaml-version
  test/passing/invalid_docstring.ml.ref
Labels: CLA Signed

#1321 Add a 'How to locally disable ocamlformat' section in the doc
  README.md
Labels: CLA Signed, Kind/Docs, no-changelog-needed

#1324 Encapsulate token filtering in Source
  lib/Fmt_ast.ml
  lib/Source.ml
  lib/Source.mli
Labels: CLA Signed, no-changelog-needed
