Repository ocaml-ppx/ocamlformat, pull requests merged in 2020-08, with the labels that each got.

#1434 Fix attributes position in labelled arguments type
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/sig_value.mli
  test/passing/sig_value.mli.ref
Labels: CLA Signed

#1433 Add missing parens around type annotation in anonymous function
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/source.ml
  test/passing/source.ml.ref
Labels: CLA Signed

#1430 Recognise eliom file extensions
  CHANGES.md
  lib/Conf.ml
  test/passing/dune.inc
  test/passing/eliom_ext.eliom
  test/passing/gen/gen.ml
Labels: CLA Signed

#1435 Release process: test next ocaml version locally
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1437 Release process: add a check for version number
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1418 Revert indicate-multiline-delimiters changes
  CHANGES.md
  lib/Ast.ml
  lib/Cmt.ml
  lib/Cmts.ml
  lib/Conf.ml
  lib/Config_option.ml
  lib/Fmt.ml
  lib/Fmt_ast.ml
  lib/Fmt_odoc.ml
  lib/Migrate_ast.ml
  lib/Non_overlapping_interval_tree.ml
  lib/Normalize.ml
  lib/Params.ml
  lib/Parse_with_comments.ml
  lib/Source.ml
  lib/Translation_unit.ml
  test/passing/apply.ml
  test/passing/comments.ml.ref
  test/passing/doc_comments.mli.ref
  test/passing/eliom_ext.eliom
  test/passing/exp_grouping-parens.ml.ref
  test/passing/exp_grouping.ml.ref
  test/passing/extensions-indent.ml.ref
  test/passing/extensions-sugar_always.ml.ref
  test/passing/extensions.ml.ref
  test/passing/first_class_module.ml
  test/passing/fun_decl.ml
  test/passing/fun_function.ml
  test/passing/function_indent-never.ml.ref
  test/passing/function_indent.ml.ref
  test/passing/infix_arg_grouping.ml
  test/passing/issue289.ml
  test/passing/ite-compact.ml.ref
  test/passing/ite-fit_or_vertical.ml.ref
  test/passing/ite-kr.ml.ref
  test/passing/ite-kw_first.ml.ref
  test/passing/ite.ml.ref
  test/passing/max_indent.ml
  test/passing/source.ml.ref
  vendor/compat/list.ml
  vendor/parse-wyc/lib/merlin_recovery.ml
  vendor/parse-wyc/lib/migrate_ast.ml
  vendor/parse-wyc/lib/parse_wyc.ml
  vendor/parse-wyc/menhir-recover/attributes.ml
  vendor/parse-wyc/menhir-recover/emitter.ml
  vendor/parse-wyc/menhir-recover/main.ml
  vendor/parse-wyc/menhir-recover/recovery_custom.ml
  vendor/parse-wyc/menhir-recover/synthesis.ml
  vendor/parse-wyc/test/unit/test_unit.ml
Labels: CLA Signed

#1436 Release process: detect tag from changelog
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1421 Fix alignment of 'then' keyword in parenthesised expression
  CHANGES.md
  lib/Params.ml
  test/passing/ite-compact.ml.ref
  test/passing/ite-compact_closing.ml.ref
  test/passing/ite-fit_or_vertical.ml.ref
  test/passing/ite-fit_or_vertical_closing.ml.ref
  test/passing/ite-fit_or_vertical_no_indicate.ml.ref
  test/passing/ite-kr.ml.ref
  test/passing/ite-kr_closing.ml.ref
  test/passing/ite-kw_first.ml.ref
  test/passing/ite-kw_first_closing.ml.ref
  test/passing/ite-kw_first_no_indicate.ml.ref
  test/passing/ite-no_indicate.ml.ref
  test/passing/ite.ml
  test/passing/ite.ml.ref
Labels: CLA Signed

#1428 Remove travis setup
  .travis.yml
  tools/travis-ci.sh
Labels: CLA Signed, no-changelog-needed

#1439 Use github usernames in CHANGES.md
  CHANGES.md
Labels: CLA Signed

#1440 Indent further args of anonymous functions
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Source.ml
Labels: CLA Signed

#1441 Update README for 0.15.0
  README.md
Labels: CLA Signed, no-changelog-needed

#1419 Fix break between keyword and expr with if-then-else=keyword-first
  CHANGES.md
  lib/Params.ml
  test/passing/ite-kw_first.ml.ref
  test/passing/ite-kw_first_closing.ml.ref
  test/passing/ite-kw_first_no_indicate.ml.ref
  test/passing/js_source.ml
  test/passing/js_source.ml.ocp
  test/passing/js_source.ml.ref
Labels: CLA Signed, JaneStreet

#1443 Release process: check and close milestone
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1438 Release process: use dune-release automatic mode
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1450 Add an upper bound for OMP
  ocamlformat.opam
Labels: CLA Signed, no-changelog-needed

#1453 Do not format vendored libraries
  .ocamlformat-ignore
Labels: no-changelog-needed
