Repository ocaml-ppx/ocamlformat, pull requests merged in 2021-09, with the labels that each got.

#1784 Attach location to the underscore of an open record pattern
  lib/Fmt_ast.ml
  lib/Loc_tree.ml
  lib/Migrate_ast.ml
  lib/Source.ml
  lib/Source.mli
  vendor/ocaml-4.13-extended/ast_helper.mli
  vendor/ocaml-4.13-extended/ast_mapper.ml
  vendor/ocaml-4.13-extended/asttypes.mli
  vendor/ocaml-4.13-extended/parser.mly
  vendor/ocaml-4.13-extended/parsetree.mli
  vendor/ocaml-4.13-extended/pprintast.ml
  vendor/parse-wyc/lib/parser.mly
Labels: CLA Signed, no-changelog-needed

#1779 Do not use ghost locations for type constraints (ocaml#10555)
  lib/Fmt_ast.ml
  test/passing/tests/comments_in_record.ml.ref
  vendor/ocaml-4.13-extended/parser.mly
  vendor/ocaml-4.13/parser.mly
  vendor/parse-wyc/lib/parser.mly
Labels: CLA Signed, no-changelog-needed

#1790 Simplify formatting of type manifests
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed

#1791 Split stdout/stderr output in the tests
  test/passing/dune.inc
  test/passing/gen/gen.ml
  test/passing/tests/error1.ml.err
  test/passing/tests/error1.ml.ref
  test/passing/tests/error2.ml.err
  test/passing/tests/error2.ml.ref
  test/passing/tests/error3.ml.err
  test/passing/tests/error3.ml.ref
  test/passing/tests/error4.ml.err
  test/passing/tests/error4.ml.ref
  test/passing/tests/invalid_docstring.ml.err
  test/passing/tests/invalid_docstring.ml.ref
  test/passing/tests/need_format.ml.err
  test/passing/tests/need_format.ml.ref
  test/passing/tests/option.ml.err
  test/passing/tests/option.ml.ref
  test/passing/tests/print_config.ml.err
  test/passing/tests/print_config.ml.ref
  test/passing/tests/verbose1.ml.err
  test/passing/tests/verbose1.ml.ref
  test/passing/tests/verbose2.ml
  test/passing/tests/verbose2.ml.enabled-if
  test/passing/tests/verbose2.ml.opts
Labels: CLA Signed, no-changelog-needed

#1794 Check whether output exceeds the margin in the tests
  test/passing/dune.inc
  test/passing/gen/gen.ml
  test/passing/tests/apply.ml.err
  test/passing/tests/assignment_operator-op_begin_line.ml.err
  test/passing/tests/attributes.ml.err
  test/passing/tests/break_cases-align.ml.err
  test/passing/tests/break_cases-all.ml.err
  test/passing/tests/break_cases-closing_on_separate_line.ml.err
  test/passing/tests/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.err
  test/passing/tests/break_cases-cosl_lnmp_cmei.ml.err
  test/passing/tests/break_cases-fit_or_vertical.ml.err
  test/passing/tests/break_cases-nested.ml.err
  test/passing/tests/break_cases-normal_indent.ml.err
  test/passing/tests/break_cases-toplevel.ml.err
  test/passing/tests/break_cases.ml.err
  test/passing/tests/break_separators-after_docked.ml.err
  test/passing/tests/break_separators-after_docked_wrap.ml.err
  test/passing/tests/break_separators-before_docked_wrap.ml.err
  test/passing/tests/break_separators-wrap.ml.err
  test/passing/tests/break_string_literals-never.ml.err
  test/passing/tests/comments.ml.err
  test/passing/tests/comments_in_record.ml.err
  test/passing/tests/compact_lists_arrays.ml.err
  test/passing/tests/doc_comments-after.ml.err
  test/passing/tests/doc_comments-before-except-val.ml.err
  test/passing/tests/doc_comments-before.ml.err
  test/passing/tests/doc_comments-no-parse-docstrings.mli.err
  test/passing/tests/doc_comments-no-wrap.mli.err
  test/passing/tests/doc_comments.ml.err
  test/passing/tests/doc_comments.mli.err
  test/passing/tests/expect_test.ml.err
  test/passing/tests/field-op_begin_line.ml.err
  test/passing/tests/first_class_module.ml.err
  test/passing/tests/issue1750.ml.err
  test/passing/tests/issue289.ml.err
  test/passing/tests/ite-compact.ml.err
  test/passing/tests/ite-compact_closing.ml.err
  test/passing/tests/ite.ml.err
  test/passing/tests/js_source.ml.err
  test/passing/tests/margin_80.ml.err
  test/passing/tests/module_attributes.ml.err
  test/passing/tests/object.ml.err
  test/passing/tests/ocp_indent_compat.ml.err
  test/passing/tests/option.ml.err
  test/passing/tests/record-loose.ml.err
  test/passing/tests/record-tight_decl.ml.err
  test/passing/tests/record.ml.err
  test/passing/tests/refs.ml.err
  test/passing/tests/single_line.mli.err
  test/passing/tests/source.ml.err
  test/passing/tests/tuple.ml.err
  test/passing/tests/tuple_less_parens.ml.err
  test/passing/tests/unicode.ml.err
  test/passing/tests/wrap_comments.ml.err
Labels: CLA Signed, no-changelog-needed

#1793 Deprecate --align-* options
  CHANGES.md
  lib/Conf.ml
  ocamlformat-help.txt
  test/passing/tests/align_cases-break_all.ml.err
  test/passing/tests/align_cases.ml.err
Labels: CLA Signed

#1749 Attach location to constants
  lib/Ast.ml
  lib/Cmts.ml
  lib/Conf.ml
  lib/Fmt_ast.ml
  lib/Indent.ml
  lib/Indent.mli
  lib/Loc_tree.ml
  lib/Loc_tree.mli
  lib/Normalize.ml
  lib/Source.ml
  lib/Source.mli
  lib/Translation_unit.ml
  test/passing/tests/attributes.ml
  vendor/diff-parsers-std-ext.patch
  vendor/ocaml-4.13-extended/ast_helper.ml
  vendor/ocaml-4.13-extended/ast_helper.mli
  vendor/ocaml-4.13-extended/ast_mapper.ml
  vendor/ocaml-4.13-extended/docstrings.ml
  vendor/ocaml-4.13-extended/parser.mly
  vendor/ocaml-4.13-extended/parsetree.mli
  vendor/ocaml-4.13-extended/pprintast.ml
  vendor/parse-wyc/lib/parser.mly
Labels: CLA Signed, no-changelog-needed

#1716 Allow disambiguated global identifiers (like t/2) so they can be formatted by tools like OCaml-LSP
  CHANGES.md
  lib/Ast.ml
  test/passing/dune.inc
  test/passing/tests/disambiguated_types.ml
  test/passing/tests/sig_value.mli
  test/passing/tests/sig_value.mli.ref
  test/rpc/rpc_test.expected
  test/rpc/rpc_test.ml
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/diff-parsers-upstream-std.patch
  vendor/ocaml-4.13-extended/lexer.mll
  vendor/ocaml-4.13-extended/parse.ml
  vendor/ocaml-4.13-extended/parser.mly
  vendor/ocaml-4.13/lexer.mll
  vendor/ocaml-4.13/parse.ml
  vendor/ocaml-4.13/parser.mly
Labels: CLA Signed

#1795 Add missing header to tools/diff-parsers/diff_parsers.ml
  tools/diff-parsers/diff_parsers.ml
Labels: CLA Signed, no-changelog-needed

#1786 Fix excessive break and wrong indentation after a short-open when 'indicate-multiline-delimiters=closing-on-separate-line'
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/open-closing-on-separate-line.ml.ref
  test/passing/tests/open.ml
  test/passing/tests/open.ml.ref
Labels: CLA Signed

#1806 Expose more Pprintast functions (ocaml#10618)
  vendor/diff-parsers-upstream-std.patch
  vendor/import-ocaml-upstream.sh
  vendor/ocaml-4.13-upstream/pprintast.ml
  vendor/ocaml-4.13-upstream/pprintast.mli
Labels: CLA Signed, no-changelog-needed

#1801 Add parentheses around type alias used as type constraint
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/source.ml
  test/passing/tests/source.ml.ref
Labels: CLA Signed

#1805 Deprecate option 'disambiguate-non-breaking-match'
  CHANGES.md
  lib/Conf.ml
  ocamlformat-help.txt
  test/passing/tests/disambiguate.ml.err
Labels: CLA Signed

#1797 Fix alignment of comments inside a tuple pattern and remove incorrect linebreak, and fix formatting of labelled arguments containing comments
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/break_separators-after.ml.ref
  test/passing/tests/break_separators-after_docked.ml.ref
  test/passing/tests/break_separators-after_docked_wrap.ml.ref
  test/passing/tests/break_separators-after_wrap.ml.ref
  test/passing/tests/break_separators-before_docked.ml.ref
  test/passing/tests/break_separators-before_docked_wrap.ml.ref
  test/passing/tests/break_separators-wrap.ml.ref
  test/passing/tests/break_separators.ml
  test/passing/tests/label_option_default_args.ml.ref
Labels: CLA Signed

#1809 Remove unused function 'Source.has_cmt_same_line_after'
  lib/Source.ml
  lib/Source.mli
Labels: CLA Signed, no-changelog-needed

#1807 Improve documentation of deprecated options and removed options
  lib/Conf.ml
  lib/Config_option.ml
  lib/Config_option.mli
  ocamlformat-help.txt
Labels: CLA Signed, no-changelog-needed

#1812 Allow configuration options to have deprecated values
  lib/Conf.ml
  lib/Config_option.ml
  lib/Config_option.mli
Labels: CLA Signed, no-changelog-needed

#1803 Deprecate 'compact' and 'sparse' profiles
  CHANGES.md
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed

#1813 Update documentation of deprecated option 'disable-outside-detected-project'
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed, no-changelog-needed

#1818 Use long option name in deprecation warning
  lib/Config_option.ml
  test/cli/deprecated_option.t
Labels: CLA Signed, no-changelog-needed

#1816 Fix documentation of option 'use-file', it should not be deprecated
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed, no-changelog-needed

#1822 Revert "Fix documentation of option 'use-file', it should not be deprecated"
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed

#1824 Set option 'enable-outside-detected-project' for test_branch.sh
  test-extra/Makefile
Labels: CLA Signed, no-changelog-needed

#1814 Emacs: only hook ocamlformat mode on tuareg/caml modes when ocamlformat is not disabled
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#1827 Define cmt_checker type to simplify break_between functions
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
Labels: no-changelog-needed
