Repository ocaml-ppx/ocamlformat, pull requests merged in 2021-02, with the labels that each got.

#1523 Support injectivity type annotations (OCaml 4.12 feature)
  CHANGES.md
  dune-project
  lib/Fmt_ast.ml
  ocamlformat.opam
  test/passing/dune.inc
  test/passing/injectivity.ml
  test/passing/injectivity.ml.minimum-ocaml-version
Labels: CLA Signed

#1605 Release 0.17.0
  CHANGES.md
  README.md
Labels: CLA Signed

#1606 Prepare the changelog for next release
  CHANGES.md
Labels: CLA Signed

#1607 Update the release procedure wrt. dune-release
  HACKING.org
Labels: CLA Signed, no-changelog-needed

#1608 Release process: document Windows binaries
  HACKING.org
Labels: no-changelog-needed
