Repository ocaml-ppx/ocamlformat, pull requests merged in 2021-10, with the labels that each got.

#1834 Handle let operator punning uniformly with other punning forms
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/tests/let_punning.ml
Labels: CLA Signed

#1833 Bring vendored Format lib up-to-date with upstream stdlib and track differences
  dune-project
  ocamlformat-rpc.opam
  ocamlformat.opam
  tools/diff-ocaml/diff_ocaml.ml
  tools/diff-ocaml/dune
  tools/diff-parsers/dune
  vendor/diff-stdlib-format.patch
  vendor/dune
  vendor/import-ocaml-upstream.sh
  vendor/ocaml-4.13-upstream/format.ml
  vendor/ocaml-4.13-upstream/format.mli
  vendor/ocamlformat_support/dune
  vendor/ocamlformat_support/format.ml
  vendor/ocamlformat_support/format.mli
  vendor/ocamlformat_support/format_.ml
  vendor/ocamlformat_support/format_.mli
Labels: CLA Signed, no-changelog-needed

#1838 Mute menhir output
  vendor/ocaml-4.13-extended/dune
  vendor/ocaml-4.13/dune
Labels: no-changelog-needed

#1839 Update README with git blame ignoreRevs example
  README.md
Labels: CLA Signed, no-changelog-needed

#1830 Fix boxing of labelled arguments
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/tests/args_grouped-conventional.ml.err
  test/passing/tests/args_grouped-conventional.ml.opts
  test/passing/tests/args_grouped-conventional.ml.ref
  test/passing/tests/args_grouped.ml
  test/passing/tests/js_source.ml.err
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
Labels: CLA Signed

#1845 Emit an error on line directives
  CHANGES.md
  test/passing/dune.inc
  test/passing/tests/line_directives.ml
  test/passing/tests/line_directives.ml.err
  test/passing/tests/line_directives.ml.ref
  test/passing/tests/line_directives.ml.should-fail
  vendor/diff-parsers-upstream-std.patch
  vendor/ocaml-4.13-extended/lexer.mll
  vendor/ocaml-4.13/lexer.mll
  vendor/parse-wyc/lib/lexer.mll
Labels: CLA Signed
