Repository ocaml-ppx/ocamlformat, pull requests merged in 2021-07, with the labels that each got.

#1704 Revert "Type identifiers can have a disambiguation suffix"
  CHANGES.md
  test/passing/tests/sig_value.mli
  test/passing/tests/sig_value.mli.ref
  test/rpc/rpc_test.expected
  test/rpc/rpc_test.ml
  vendor/ocaml-4.12/lexer.mll
  vendor/ocaml-4.12/parser.mly
Labels: CLA Signed

#1696 Fix parentheses around successive unary operations
  CHANGES.md
  lib/Ast.ml
  test/passing/tests/unary.ml
  test/passing/tests/unary.ml.ref
Labels: CLA Signed

#1695 Fix normalization of odoc paragraphs
  CHANGES.md
  lib/Normalize.ml
  test/passing/tests/doc_comments-after.ml.ref
  test/passing/tests/doc_comments-before-except-val.ml.ref
  test/passing/tests/doc_comments-before.ml.ref
  test/passing/tests/doc_comments.ml
  test/passing/tests/doc_comments.ml.ref
Labels: CLA Signed

#1680 Implement OCaml 4.13 features
  CHANGES.md
  dune-project
  lib/Ast.ml
  lib/Exposed.ml
  lib/Fmt_ast.ml
  lib/Parse_with_comments.ml
  lib/Sugar.ml
  lib/Sugar.mli
  lib/dune
  ocamlformat-rpc-lib.opam
  ocamlformat-rpc.opam
  ocamlformat.opam
  test/failing/tests/indent_empty.ml.broken-ref
  test/failing/tests/js_functor.ml.broken-ref
  test/failing/tests/pattern.ml.broken-ref
  test/failing/tests/unit_classes.ml.broken-ref
  test/failing/tests/unit_extensions.ml.broken-ref
  test/failing/tests/unit_modtypes.ml.broken-ref
  test/passing/dune.inc
  test/passing/tests/let_punning.ml
  test/passing/tests/mod_type_subst.ml
  test/passing/tests/named_existentials.ml
  vendor/ocaml-4.13/ast_helper.ml
  vendor/ocaml-4.13/ast_helper.mli
  vendor/ocaml-4.13/ast_mapper.ml
  vendor/ocaml-4.13/ast_mapper.mli
  vendor/ocaml-4.13/asttypes.mli
  vendor/ocaml-4.13/docstrings.ml
  vendor/ocaml-4.13/docstrings.mli
  vendor/ocaml-4.13/dune
  vendor/ocaml-4.13/lexer.mll
  vendor/ocaml-4.13/location.ml
  vendor/ocaml-4.13/location.mli
  vendor/ocaml-4.13/longident.ml
  vendor/ocaml-4.13/longident.mli
  vendor/ocaml-4.13/parse.ml
  vendor/ocaml-4.13/parse.mli
  vendor/ocaml-4.13/parser.mly
  vendor/ocaml-4.13/parsetree.mli
  vendor/ocaml-4.13/pprintast.ml
  vendor/ocaml-4.13/pprintast.mli
  vendor/ocaml-4.13/syntaxerr.ml
  vendor/ocaml-4.13/syntaxerr.mli
  vendor/ocaml-4.13/warnings.ml
  vendor/ocaml-4.13/warnings.mli
  vendor/ocamlformat-stdlib/dune
  vendor/parse-wyc/lib/dune
  vendor/parse-wyc/lib/let_binding.mli
  vendor/parse-wyc/lib/lexer.mll
  vendor/parse-wyc/lib/parse_wyc.ml
  vendor/parse-wyc/lib/parser.mly
  vendor/parse-wyc/test/unit/dune
  vendor/parse-wyc/test/unit/test_unit.ml
  vendor/parser-shims/parser_shims.ml
  vendor/parser-shims/parser_shims.mli
Labels: CLA Signed

#1705 README: fix normalization function name in overview section
  README.md
Labels: CLA Signed, Kind/Docs, no-changelog-needed

#1709 Include LGPL 2.1 license of compiler vendored code
  dune-project
  ocamlformat-rpc.opam
  ocamlformat.opam
  vendor/ocaml-4.13/LICENSE
Labels: CLA Signed, no-changelog-needed

#1683 Depend on odoc-parser instead of odoc
  CHANGES.md
  dune-project
  lib/Docstring.ml
  lib/Docstring.mli
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
  lib/Normalize.ml
  lib/dune
  ocamlformat-rpc.opam
  ocamlformat.opam
  test/passing/tests/invalid_docstring.ml.ref
Labels: CLA Signed

#1711 Add missing break between pattern and attribute
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/attributes.ml
  test/passing/tests/extensions-indent.ml.ref
  test/passing/tests/extensions.ml.ref
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
  test/passing/tests/label_option_default_args.ml.ref
  test/passing/tests/object.ml
  test/passing/tests/shortcut_ext_attr.ml
  test/passing/tests/source.ml.ref
  test/passing/tests/string.ml.ref
  test/passing/tests/types-compact-space_around-docked.ml.ref
  test/passing/tests/types-compact-space_around.ml.ref
  test/passing/tests/types-compact.ml.ref
  test/passing/tests/types-indent.ml.ref
  test/passing/tests/types-sparse-space_around.ml.ref
  test/passing/tests/types-sparse.ml.ref
  test/passing/tests/types.ml
Labels: CLA Signed

#1708 Add missing parentheses around expression having attributes or comments inside a shorthand let-open clause
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/open-closing-on-separate-line.ml.ref
  test/passing/tests/open.ml
  test/passing/tests/open.ml.ref
Labels: CLA Signed

#1702 Add script to build ocamlformat with mingw64
  .github/workflows/build-mingw64.yml
  .gitignore
  CHANGES.md
  HACKING.org
  tools/build-mingw64.sh
Labels: CLA Signed, no-changelog-needed

#1714 Fix unstable broken-ref test
  lib/Translation_unit.ml
  test/failing/tests/unstable_docstrings.mli.broken-ref
Labels: CLA Signed, no-changelog-needed

#1713 Format Odoc code block metadata fields
  CHANGES.md
  lib/Fmt_odoc.ml
  lib/Normalize.ml
  test/passing/tests/doc_comments-after.ml.ref
  test/passing/tests/doc_comments-before-except-val.ml.ref
  test/passing/tests/doc_comments-before.ml.ref
  test/passing/tests/doc_comments.ml
  test/passing/tests/doc_comments.ml.ref
Labels: CLA Signed

#1718 Convert test for option 'parse-docstrings=false'
  test/passing/dune.inc
  test/passing/tests/doc_comments-no-parse-docstrings.mli.opts
  test/passing/tests/doc_comments-no-parse-docstrings.mli.ref
  test/passing/tests/doc_comments-parse-docstrings.mli.opts
Labels: CLA Signed, no-changelog-needed

#1722 README: use ocamlformat from current switch in Vim
  README.md
Labels: CLA Signed, no-changelog-needed

#1717 Revert infix-form list formatting to pre-0.17.0
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/tests/list-space_around.ml.ref
  test/passing/tests/list.ml
Labels: CLA Signed

#1703 Add 'line-endings' option to specify line endings used in the formatted output
  .ocamlformat
  CHANGES.md
  bin/ocamlformat/main.ml
  lib/Conf.ml
  lib/Conf.mli
  lib/Translation_unit.ml
  ocamlformat-help.txt
  test/passing/dune.inc
  test/passing/tests/crlf_to_crlf.ml
  test/passing/tests/crlf_to_crlf.ml.opts
  test/passing/tests/crlf_to_crlf.ml.ref
  test/passing/tests/crlf_to_lf.ml
  test/passing/tests/crlf_to_lf.ml.opts
  test/passing/tests/crlf_to_lf.ml.ref
  test/passing/tests/print_config.ml.ref
  test/passing/tests/verbose1.ml.ref
  test/passing/tests/verbose2.ml.ref
Labels: CLA Signed

#1724 Update the README for the 0.19.0 release
  CHANGES.md
  README.md
Labels: CLA Signed

#1725 Upstream opam files changes made for 0.19.0
  dune-project
  ocamlformat-rpc.opam
  ocamlformat-rpc.opam.template
  ocamlformat.opam
  ocamlformat.opam.template
Labels: CLA Signed, no-changelog-needed

#1726 Update changelog for next release
  CHANGES.md
Labels: CLA Signed

#1727 Add missing copyright header
  tools/build-mingw64.sh
Labels: CLA Signed, no-changelog-needed

#1731 Fix normalization of sequences of expressions
  CHANGES.md
  lib/Normalize.ml
  test/passing/tests/sequence-preserve.ml.ref
  test/passing/tests/sequence.ml
  test/passing/tests/sequence.ml.ref
Labels: CLA Signed

#1734 Add missing parenthesis around constrained pattern in class
  CHANGES.md
  lib/Ast.ml
  test/passing/tests/object.ml
Labels: CLA Signed

#1739 Support sugared form of coercions in let bindings
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/dune.inc
  test/passing/tests/coerce.ml
Labels: CLA Signed

#1742 Remove side-effects of Fmt.list_k that caused comments to be dropped
  lib/Fmt.ml
  test/unit/test_fmt.ml
Labels: CLA Signed, no-changelog-needed

#1744 Extract a fmt_attribute function from fmt_attributes
  lib/Fmt_ast.ml
Labels: CLA Signed, no-changelog-needed

#1745 Make the formatting mode of comments more explicit
  lib/Cmt.ml
Labels: CLA Signed, no-changelog-needed

#1740 Add missing parentheses around constructor used as indexing op
  CHANGES.md
  lib/Ast.ml
  test/passing/tests/index_op.ml
Labels: CLA Signed

#1752 Fix the handling of .ocamlformat-ignore on Windows
  CHANGES.md
  lib/Conf.ml
Labels: CLA Signed, Host/Windows

#1755 Update vendored parser with ocaml#10441
  vendor/ocaml-4.13/parser.mly
  vendor/parse-wyc/lib/parser.mly
Labels: CLA Signed, no-changelog-needed

#1756 Handle punned labelled arguments with type constraint in function applications (ocaml#10434)
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/apply.ml
  vendor/ocaml-4.13/parser.mly
  vendor/parse-wyc/lib/parser.mly
Labels: CLA Signed
