Repository ocaml-ppx/ocamlformat, pull requests merged in 2021-12, with the labels that each got.

#1937 Simplify generative modules
  lib/Fmt_ast.ml
Labels: CLA Signed, no changelog

#1939 Fix position of comments preceding Pmod_ident
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/comments.ml.ref
Labels: CLA Signed

#1934 Remove unnecessary surrounding parentheses for immediate objects (OCaml 4.14 feature)
  CHANGES.md
  lib/Ast.ml
  test/passing/dune.inc
  test/passing/tests/object_expr-414.ml.opts
  test/passing/tests/object_expr-414.ml.ref
  test/passing/tests/object_expr.ml
  test/passing/tests/object_expr.ml.ref
Labels: CLA Signed

#1929 Make the formatting of attributes and docstrings more consistent
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/module_attributes.ml.err
  test/passing/tests/module_attributes.ml.ref
  test/passing/tests/source.ml.err
  test/passing/tests/source.ml.ref
Labels: CLA Signed

#1942 Fix stabilization of comments inside attributes
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/attributes.ml
  test/passing/tests/js_source.ml
  test/passing/tests/js_source.ml.err
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
Labels: CLA Signed

#1945 Fix position of comments following a record field
  CHANGES.md
  lib/Ast.ml
  lib/Cmts.ml
  test/passing/tests/comments.ml.ref
  test/passing/tests/comments_in_record.ml
  test/passing/tests/comments_in_record.ml.ref
Labels: CLA Signed

#1885 Break arg group when there is a comment after
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/args_grouped-conventional.ml.err
  test/passing/tests/args_grouped-conventional.ml.ref
  test/passing/tests/args_grouped.ml
  test/passing/tests/comments_args.ml.ref
  test/passing/tests/source.ml
  test/passing/tests/source.ml.ref
Labels: CLA Signed

#1946 Allow ocamlformat to be compiled on OCaml 4.14
  dune-project
  ocamlformat-bench.opam
  ocamlformat-rpc-lib.opam
  ocamlformat-rpc.opam
  ocamlformat.opam
Labels: CLA Signed, no changelog

#1947 Update README and CHANGES for 0.20.0
  CHANGES.md
  README.md
Labels: CLA Signed, no changelog

#1948 Prepare changelog for next release
  CHANGES.md
Labels: CLA Signed

#1949 Depend on ocaml-version.3.3.0 to handle OCaml 4.13.0
  dune-project
  ocamlformat-bench.opam
  ocamlformat-rpc.opam
  ocamlformat.opam
Labels: CLA Signed, no changelog

#1950 Update the "Create a Windows asset" workflow
  HACKING.org
Labels: CLA Signed, no changelog

#1952 Move normalizing functions into corresponding AST module
  lib/Cmt.ml
  lib/Cmt.mli
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Docstring.ml
  lib/Docstring.mli
  lib/Extended_ast.ml
  lib/Extended_ast.mli
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
  lib/Normalize.ml
  lib/Normalize.mli
  lib/Std_ast.ml
  lib/Std_ast.mli
  lib/Translation_unit.ml
Labels: CLA Signed, no changelog

#1954 Move Asttypes module from Migrate_ast to Extended_ast
  lib/Extended_ast.ml
  lib/Extended_ast.mli
  lib/Fmt_ast.ml
  lib/Migrate_ast.ml
  lib/Migrate_ast.mli
Labels: CLA Signed, no changelog

#1955 Define config option error type
  bin/ocamlformat-rpc/main.ml
  lib/Conf.ml
  lib/Conf.mli
  lib/Config_option.ml
  lib/Config_option.mli
Labels: CLA Signed, no changelog

#1956 Move docstring normalizing functions to Docstring
  lib/Docstring.ml
  lib/Docstring.mli
  lib/Fmt_ast.ml
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
  lib/Std_ast.ml
  lib/Std_ast.mli
Labels: CLA Signed, no changelog

#1843 Update to odoc-parser 1.0.0
  CHANGES.md
  dune-project
  lib/Docstring.ml
  lib/Fmt_odoc.ml
  ocamlformat-bench.opam
  ocamlformat-rpc.opam
  ocamlformat.opam
  test/passing/tests/doc_comments-no-parse-docstrings.mli.err
  test/passing/tests/doc_comments-no-parse-docstrings.mli.ref
  test/passing/tests/doc_comments-no-wrap.mli.err
  test/passing/tests/doc_comments-no-wrap.mli.ref
  test/passing/tests/doc_comments.mli
  test/passing/tests/doc_comments.mli.err
  test/passing/tests/doc_comments.mli.ref
Labels: CLA Signed

#1959 Update README and CHANGES for 0.20.1
  CHANGES.md
  README.md
Labels: no changelog

#1960 Prepare changelog for next release
  CHANGES.md
Labels: CLA Signed, no changelog

#1961 Update release procedure: list all packages except ocamlformat-bench
  HACKING.org
Labels: CLA Signed, no changelog

#1962 Exp.is_trivial does not need the configuration
  lib/Ast.ml
Labels: CLA Signed, no changelog

#1922 Move documentation from the README to odoc pages
  HACKING.org
  README.md
  doc/doc_comments.mld
  doc/dune
  doc/editor_setup.mld
  doc/faq.mld
  doc/getting_started.mld
  doc/howtos.mld
  doc/index.mld
Labels: CLA Signed, Kind/Docs, no changelog
