Repository ocaml-ppx/ocamlformat, pull requests merged in 2022-07, with the labels that each got.

#2116 Closing parentheses of local open now comply with 'indicate-multiline-delimiters'
  CHANGES.md
  lib/Ast.ml
  lib/Conf.ml
  lib/Config_option.ml
  lib/Fmt_ast.ml
  lib/Source.ml
  lib/Source.mli
  test/passing/tests/comments.ml.ref
  test/passing/tests/let_in_constr.ml
  test/passing/tests/open.ml.ref
  test/passing/tests/source.ml.ref
  vendor/diff-parsers-std-ext.patch
  vendor/parser-extended/ast_helper.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed

#2117 Simplify formatting of infix expressions
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
Labels: CLA Signed, no changelog

#2119 Fix byte-compile warnings
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#2122 ocamlformat 0.23.0 is not compatible with odoc-parser.2.0.0
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no changelog

#2123 Support odoc-parser.2.0.0
  CHANGES.md
  dune-project
  lib/Docstring.ml
  lib/Fmt_odoc.ml
  ocamlformat.opam
  test/passing/tests/doc_comments-no-parse-docstrings.mli.err
  test/passing/tests/doc_comments-no-parse-docstrings.mli.ref
  test/passing/tests/doc_comments-no-wrap.mli.err
  test/passing/tests/doc_comments-no-wrap.mli.ref
  test/passing/tests/doc_comments.mli
  test/passing/tests/doc_comments.mli.err
  test/passing/tests/doc_comments.mli.ref
Labels: CLA Signed

#2130 Remove {post} tag on ocamlformat-rpc-lib dep
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no changelog

#2129 Fix indentation when ocamlformat is disabled on an expression
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/tests/disabled_attr.ml
Labels: CLA Signed

#2131 Reset max-indent when 'max-indent' is not set
  CHANGES.md
  lib/Fmt.ml
  lib/Fmt.mli
  lib/Translation_unit.ml
  test/cli/multiple_projects.t
Labels: CLA Signed

#2132 Mention 'entr' in the manual to reformat files on save
  doc/editor_setup.mld
Labels: CLA Signed, Kind/Docs, no changelog

#2133 Bump ocaml-re dependency to 1.10.3
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no changelog

#2055 CI: add Github Action workflow for MacOS and Windows
  .github/workflows/build.yml
  lib/Eol_compat.ml
  lib/Eol_compat.mli
  lib/Toplevel_lexer.mll
  lib/Translation_unit.ml
  test/cli/dune
  test/failing/dune
  test/passing/dune
  test/passing/dune.inc
  test/passing/tests/break_cases-align.ml.enabled-if
  test/passing/tests/break_cases-all.ml.enabled-if
  test/passing/tests/break_cases-closing_on_separate_line.ml.enabled-if
  test/passing/tests/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.enabled-if
  test/passing/tests/break_cases-cosl_lnmp_cmei.ml.enabled-if
  test/passing/tests/break_cases-fit_or_vertical.ml.enabled-if
  test/passing/tests/break_cases-nested.ml.enabled-if
  test/passing/tests/break_cases-normal_indent.ml.enabled-if
  test/passing/tests/cinaps.ml.enabled-if
  test/passing/tests/comment_header.ml.enabled-if
  test/passing/tests/doc_comments-no-wrap.mli.enabled-if
  test/passing/tests/doc_comments.mli.enabled-if
  test/passing/tests/escaped_nl.ml.enabled-if
  test/passing/tests/js_to_do.ml.enabled-if
  test/passing/tests/reformat_string.ml.enabled-if
  test/passing/tests/wrap_comments.ml.enabled-if
  test/unit/test_eol_compat.ml
  test/unit/test_eol_compat.mli
  test/unit/test_indent.ml
  test/unit/test_translation_unit.ml
  test/unit/test_unit.ml
  vendor/parser-recovery/test/expect/dune
Labels: CLA Signed, no changelog
