Repository ocaml-ppx/ocamlformat, pull requests merged in 2022-05, with the labels that each got.

#2067 Fix build for OCaml 5
  ocamlformat.opam
  vendor/parser-recovery/menhir-recover/emitter.ml
Labels: CLA Signed, no changelog

#2064 Set ocaml-version to a fixed version by default to avoid reproducibility issues and surprising behaviours
  CHANGES.md
  lib/Conf.ml
  lib/Config_option.ml
  lib/Config_option.mli
  ocamlformat-help.txt
  ocamlformat-rpc-help.txt
Labels: CLA Signed

#2070 Remove upper bound of ocaml version for 5.00
  dune-project
  ocamlformat-bench.opam
  ocamlformat-rpc-lib.opam
Labels: CLA Signed, no changelog

#2071 Update Parsetree according to upstream ocaml (commit dd44a25)
  vendor/diff-parsers-std-ext.patch
  vendor/diff-parsers-upstream-std.patch
  vendor/import-ocaml-upstream.sh
  vendor/parser-extended/asttypes.mli
  vendor/parser-extended/parsetree.mli
  vendor/parser-standard/asttypes.mli
  vendor/parser-standard/parsetree.mli
  vendor/parser-upstream/asttypes.mli
  vendor/parser-upstream/parsetree.mli
Labels: CLA Signed, no changelog

#2074 Cancel the deprecations of options that are not set by the preset profiles
  CHANGES.md
  lib/Conf.ml
  test/cli/deprecated_option.t
  test/passing/tests/align_cases-break_all.ml.err
  test/passing/tests/apply.ml.err
  test/passing/tests/break_before_in-auto.ml.err
  test/passing/tests/break_before_in.ml.err
  test/passing/tests/break_cases-align.ml.err
  test/passing/tests/break_cases-all.ml.err
  test/passing/tests/break_cases-closing_on_separate_line.ml.err
  test/passing/tests/break_cases-closing_on_separate_line_leading_nested_match_parens.ml.err
  test/passing/tests/break_cases-cosl_lnmp_cmei.ml.err
  test/passing/tests/break_cases-normal_indent.ml.err
  test/passing/tests/break_cases-toplevel.ml.err
  test/passing/tests/break_fun_decl-smart.ml.err
  test/passing/tests/break_separators-after_docked_wrap.ml.err
  test/passing/tests/break_separators-after_wrap.ml.err
  test/passing/tests/break_separators-before_docked_wrap.ml.err
  test/passing/tests/break_separators-wrap.ml.err
  test/passing/tests/break_sequence_before.ml.err
  test/passing/tests/break_string_literals-never.ml.err
  test/passing/tests/break_string_literals.ml.err
  test/passing/tests/break_struct.ml.err
  test/passing/tests/cases_exp_grouping.ml.err
  test/passing/tests/compact_lists_arrays.ml.err
  test/passing/tests/disambiguate.ml.err
  test/passing/tests/exp_grouping-parens.ml.err
  test/passing/tests/exp_grouping.ml.err
  test/passing/tests/extensions-indent.ml.err
  test/passing/tests/extensions-indent.mli.err
  test/passing/tests/first_class_module.ml.err
  test/passing/tests/function_indent-never.ml.err
  test/passing/tests/function_indent.ml.err
  test/passing/tests/indicate_multiline_delimiters-cosl.ml.err
  test/passing/tests/ite-compact_closing.ml.err
  test/passing/tests/ite-fit_or_vertical.ml.err
  test/passing/tests/ite-fit_or_vertical_closing.ml.err
  test/passing/tests/ite-fit_or_vertical_no_indicate.ml.err
  test/passing/tests/ite-kr.ml.err
  test/passing/tests/ite-kr_closing.ml.err
  test/passing/tests/ite-kw_first_closing.ml.err
  test/passing/tests/let_binding-in_indent.ml.err
  test/passing/tests/let_binding-indent.ml.err
  test/passing/tests/let_binding_spacing-sparse.ml.err
  test/passing/tests/match_indent-never.ml.err
  test/passing/tests/match_indent.ml.err
  test/passing/tests/module_item_spacing-preserve.ml.err
  test/passing/tests/module_item_spacing.mli.err
  test/passing/tests/open-closing-on-separate-line.ml.err
  test/passing/tests/parens_tuple_patterns.ml.err
  test/passing/tests/sequence-preserve.ml.err
  test/passing/tests/sequence.ml.err
  test/passing/tests/str_value.ml.err
  test/passing/tests/try_with_or_pattern.ml.err
  test/passing/tests/types-indent.ml.err
Labels: CLA Signed

#2076 Remove options 'align-cases', 'align-constructors-decl' and 'align-variants-decl'
  CHANGES.md
  lib/Conf.ml
  lib/Conf.mli
  lib/Config_option.ml
  lib/Fmt_ast.ml
  ocamlformat-help.txt
  test/passing/dune.inc
  test/passing/tests/align_cases-break_all.ml.err
  test/passing/tests/align_cases-break_all.ml.opts
  test/passing/tests/align_cases-break_all.ml.ref
  test/passing/tests/align_cases.ml
  test/passing/tests/align_cases.ml.err
  test/passing/tests/align_cases.ml.opts
  test/passing/tests/print_config.ml.err
  test/passing/tests/verbose1.ml.err
Labels: CLA Signed

#2077 Remove option 'disable-outside-detected-project'
  CHANGES.md
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed

#2082 emacs: apply '--range' option with '--numeric'
  CHANGES.md
  emacs/ocamlformat.el
Labels: CLA Signed

#2083 Improve documentation of option 'field-space'
  lib/Conf.ml
  ocamlformat-help.txt
Labels: CLA Signed, Kind/Docs, no changelog

#2032 Preserve position of comments located after the semi-colon of the last element of lists/arrays/records
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Fmt_ast.ml
  test/passing/dune.inc
  test/passing/tests/collections-conventional.ml.opts
  test/passing/tests/collections-conventional.ml.ref
  test/passing/tests/collections-janestreet.ml.opts
  test/passing/tests/collections-janestreet.ml.ref
  test/passing/tests/collections.ml
  test/passing/tests/collections.ml.opts
  test/passing/tests/collections.ml.ref
Labels: CLA Signed

#2086 github actions: Check the version number of Windows binaries
  tools/build-mingw64.sh
Labels: CLA Signed, no changelog, Host/Windows

#2085 github actions:Do not apply 'dune subst' to override the version number of Windows binaries
  tools/build-mingw64.sh
Labels: CLA Signed, no changelog, Host/Windows

#2087 Revert "Fix version number of Windows binaries (#2085)"
  tools/build-mingw64.sh
Labels: CLA Signed, no changelog

#2084 Display a warning for redundant option definitions when using '--print-config'
  CHANGES.md
  lib/Config_option.ml
  test/cli/print_config.t
Labels: CLA Signed

#2089 Add dependency to ocamlformat-rpc-lib
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no changelog

#2090 Build parser-recovery tests only for ocamlformat package
  vendor/parser-recovery/test/expect/gen/dune
Labels: CLA Signed, no changelog

#2091 Ignore patch number for option removal/deprecation messages
  lib/Conf.ml
  lib/Version.ml
  lib/Version.mli
  ocamlformat-help.txt
  test/cli/removed_option.t
Labels: CLA Signed, no changelog

#2088 Add a script generating a formatting preview of the upcoming release
  tools/preview_new_release.sh
  tools/projects.data
Labels: CLA Signed, no changelog

#2093 Only enable parser-recovery tests for package ocamlformat
  vendor/parser-recovery/test/expect/dune.inc
  vendor/parser-recovery/test/expect/gen/gen.ml
Labels: CLA Signed, no changelog

#2095 Prepare changelog for next release
  CHANGES.md
Labels: CLA Signed

#2097 Preserve comments around object open/close flag
  CHANGES.md
  lib/Extended_ast.ml
  lib/Extended_ast.mli
  lib/Fmt_ast.ml
  test/passing/tests/comments.ml.ref
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/diff-parsers-std-ext.patch
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/asttypes.mli
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed
