Repository ocaml-ppx/ocamlformat, pull requests merged in 2022-02, with the labels that each got.

#1999 ocamlformat-rpc: improve the documentation of the API
  bin/ocamlformat-rpc/dune
  bin/ocamlformat-rpc/index.mld
  bin/ocamlformat-rpc/main.ml
  lib-rpc/IO.ml
  lib-rpc/ocamlformat_rpc_lib.ml
  lib-rpc/ocamlformat_rpc_lib.mli
  ocamlformat-rpc-help.txt
Labels: CLA Signed, Kind/Docs, no changelog

#2004 Apply 'sequence-style' to add a space before ';;' between toplevel items
  CHANGES.md
  bin/ocamlformat-rpc/main.ml
  bin/ocamlformat/main.ml
  lib/Fmt_ast.ml
  test/cli/repl_file_errors.t/run.t
  test/passing/tests/apply.ml
  test/passing/tests/attributes.ml
  test/passing/tests/cinaps.ml.ref
  test/passing/tests/doc_comments-no-wrap.mli.ref
  test/passing/tests/doc_comments.mli.ref
  test/passing/tests/extensions-indent.ml.ref
  test/passing/tests/extensions.ml.ref
  test/passing/tests/index_op.ml
  test/passing/tests/infix_bind-break.ml.ref
  test/passing/tests/infix_bind-fit_or_vertical-break.ml.ref
  test/passing/tests/infix_bind-fit_or_vertical.ml.ref
  test/passing/tests/infix_bind.ml
  test/passing/tests/object.ml
  test/passing/tests/precedence.ml
  test/passing/tests/repl.ml.ref
  test/passing/tests/repl.mli.ref
  test/passing/tests/source.ml.ref
  test/passing/tests/string.ml.ref
  test/passing/tests/string_array.ml
  test/passing/tests/symbol.ml
  test/passing/tests/tuple.ml
  test/passing/tests/tuple_less_parens.ml
  test/passing/tests/use_file.mlt
Labels: CLA Signed

#2005 test_branch.sh: Include janestreet and community projects to the list
  test-extra/Makefile
Labels: CLA Signed, no changelog

#2014 [nebuchadnezzar][opam] force odoc-parser < 1.0
  ocamlformat.opam
Labels: CLA Signed

#2015 Do not use dune 3.0
  dune-project
  ocamlformat.opam
Labels: CLA Signed, no changelog

#2017 Move type code_formatter to Fmt
  lib/Cmts.mli
  lib/Docstring.ml
  lib/Docstring.mli
  lib/Fmt.ml
  lib/Fmt.mli
  lib/Fmt_ast.ml
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
Labels: CLA Signed, no changelog

#2013 Add attributes on infix operator application
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/infix_bind-break.ml.ref
  test/passing/tests/infix_bind-fit_or_vertical-break.ml.ref
  test/passing/tests/infix_bind-fit_or_vertical.ml.ref
  test/passing/tests/infix_bind.ml
Labels: CLA Signed

#2021 README.md: Latest version of ocamlformat
  README.md
Labels: CLA Signed, no changelog

#2022 Expose ocamlformat libraries
  bench/bench.ml
  bench/dune
  bin/ocamlformat-rpc/dune
  bin/ocamlformat-rpc/main.ml
  bin/ocamlformat/dune
  bin/ocamlformat/main.ml
  dune-project
  lib/dune
  ocamlformat-bench.opam
  ocamlformat-rpc.opam
  test/unit/dune
  test/unit/test_ast.ml
  test/unit/test_fmt.ml
  test/unit/test_indent.ml
  test/unit/test_literal_lexer.ml
  test/unit/test_translation_unit.ml
  test/unit/test_unit.ml
  vendor/ocaml-4.13-extended/dune
  vendor/ocaml-4.13/dune
  vendor/ocaml-common/dune
  vendor/ocamlformat-stdlib/cmdliner_ext.mli
  vendor/ocamlformat-stdlib/dune
  vendor/ocamlformat_support/dune
  vendor/parse-wyc/lib/dune
  vendor/parser-shims/dune
Labels: CLA Signed, no changelog

#2025 Fix indentation of constraints of a package type pattern
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/module_type.ml
Labels: CLA Signed

#2023 Platform: Move RPC code to ocamlformat-rpc library
  bin/ocamlformat-rpc/dune
  bin/ocamlformat-rpc/main.ml
  lib-rpc-server/dune
  lib-rpc-server/ocamlformat_rpc.ml
Labels: CLA Signed, no changelog

#2026 Release 0.21.0
  CHANGES.md
  README.md
  doc/faq.mld
  doc/getting_started.mld
Labels: CLA Signed

#2029 ocamlformat-rpc-lib: Add missing constraint csexp >= 1.4.0
  dune-project
  ocamlformat-rpc-lib.opam
Labels: CLA Signed, no changelog

#2030 Prepare the changelog for next release
  CHANGES.md
Labels: CLA Signed, no changelog
