Repository ocaml-ppx/ocamlformat, pull requests merged in 2022-12, with the labels that each got.

#2212 Merge AST mappers
  lib/Extended_ast.ml
Labels: CLA Signed, no changelog

#2205 Fix mingw64 build script, automate Windows release asset
  .github/workflows/build-mingw64.yml
  CHANGES.md
  tools/build-mingw64.sh
Labels: CLA Signed

#2217 Fix spacing between recursive module bindings and recursive module declarations
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  test/passing/tests/comments.ml.err
  test/passing/tests/comments.ml.ref
  test/passing/tests/extensions-indent.ml.ref
  test/passing/tests/extensions-indent.mli.ref
  test/passing/tests/extensions.ml.ref
  test/passing/tests/extensions.mli
  test/passing/tests/module_type.ml
  test/passing/tests/recmod.mli
  test/passing/tests/shortcut_ext_attr.ml
  test/passing/tests/source.ml.err
  test/passing/tests/source.ml.ref
  vendor/parser-extended/printast.ml
  vendor/parser-extended/printast.mli
Labels: CLA Signed

#2219 Re-use the type let_binding from the parser instead of value_binding, improve the spacing of let-bindings regarding of having extension or comments
  CHANGES.md
  lib/Ast.ml
  lib/Ast.mli
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  test/passing/tests/js_source.ml.err
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/parser-extended/ast_helper.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/ast_mapper.mli
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-extended/printast.mli
  vendor/parser-recovery/lib/dune
  vendor/parser-recovery/lib/let_binding.mli
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed

#2218 ocamlformat-rpc: use binary mode for stdin/stdout
  CHANGES.md
  lib-rpc-server/ocamlformat_rpc.ml
Labels: CLA Signed

#2206 Fix interpretation of glob patterns in .ocamlformat-ignore under Windows
  CHANGES.md
  lib/bin_conf/Bin_conf.ml
Labels: CLA Signed, Host/Windows

#2221 Re-use the type functor_parameter from the parser instead of functor_arg
  lib/Fmt_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
Labels: CLA Signed, no changelog

#2222 Make the README more engaging
  README.md
Labels: CLA Signed, Kind/Docs, no changelog
