Repository ocaml-ppx/ocamlformat, pull requests merged in 2023-09, with the labels that each got.

#2424 Backport dead code in vendored parsers
  test/failing/tests/unit_lex.ml.broken-ref
  test/failing/tests/unit_values.ml.broken-ref
  test/passing/tests/error3.ml.err
  test/passing/tests/error4.ml.err
  test/passing/tests/option.ml.err
  test/unit/test_translation_unit.ml
  vendor/ocaml-common/location.ml
  vendor/ocaml-common/location.mli
  vendor/parser-extended/parser.mly
  vendor/parser-shims/parser_shims.ml
  vendor/parser-shims/parser_shims.mli
  vendor/parser-standard/ast_mapper.ml
  vendor/parser-standard/parser.mly
Labels: no changelog

#2430 test_branch: Print tested versions
  .github/workflows/build-linux.yml
  tools/test_branch.sh
Labels: no changelog

#2433 ocamlformat.el (ocamlformat-before-save): support caml-mode
  emacs/ocamlformat.el
Labels: no changelog, Integration/emacs

#2431 Improvements to the preview script
  tools/preview_new_release.sh
  tools/projects.data
Labels: no changelog

#2449 Remove .mli files in vendored parsers
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.mli
  vendor/parser-extended/docstrings.mli
  vendor/parser-extended/parse.mli
  vendor/parser-extended/printast.mli
  vendor/parser-standard/ast_helper.mli
  vendor/parser-standard/ast_mapper.ml
  vendor/parser-standard/ast_mapper.mli
  vendor/parser-standard/docstrings.mli
  vendor/parser-standard/parse.mli
  vendor/parser-standard/printast.mli
Labels: no changelog

#2444 Sanitize result types
  dune
  dune-project
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
  lib/Translation_unit.ml
  lib/bin_conf/Bin_conf.ml
  lib/bin_conf/dune
  lib/dune
  ocamlformat-lib.opam
  vendor/ocamlformat-result/dune
  vendor/ocamlformat-result/ocamlformat_result.ml
  vendor/ocamlformat-result/ocamlformat_result.mli
  vendor/odoc-parser/dune
Labels: no changelog

#2446 Add a page about how the configuration is computed
  doc/configuration.mld
  doc/editor_setup.mld
  doc/getting_started.mld
  doc/index.mld
Labels: Kind/docs, no changelog

#2452 Update issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/style_suggestion.md
Labels: no changelog
