Repository ocaml-ppx/ocamlformat, pull requests merged in 2023-01, with the labels that each got.

#2226 Upgrade vendored ocaml to commit fea5ca5
  test/failing/tests/ppx_stritem_ext.ml.broken-ref
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/diff-parsers-upstream-std.patch
  vendor/diff-stdlib-format.patch
  vendor/import-ocaml-upstream.sh
  vendor/ocaml-common/syntaxerr.ml
  vendor/ocaml-common/syntaxerr.mli
  vendor/parser-extended/lexer.mll
  vendor/parser-extended/parse.ml
  vendor/parser-extended/parser.mly
  vendor/parser-recovery/lib/lexer.mll
  vendor/parser-recovery/lib/parser.mly
  vendor/parser-standard/lexer.mll
  vendor/parser-standard/parse.ml
  vendor/parser-standard/parser.mly
  vendor/parser-upstream/format.ml
  vendor/parser-upstream/format.mli
  vendor/parser-upstream/lexer.mll
  vendor/parser-upstream/parse.ml
  vendor/parser-upstream/parser.mly
Labels: CLA Signed, no changelog

#2216 Make pcsig_self optionnal
  lib/Ast.ml
  lib/Fmt_ast.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
  vendor/parser-recovery/test/expect/signature/unclosed_class_sig.mli.ref
  vendor/parser-recovery/test/expect/structure/unclosed_class6.ml.ref
Labels: CLA Signed, no changelog

#2231 docs: update FAQ to use recursive glob for ignoring
  .ocamlformat-ignore
  doc/faq.mld
Labels: CLA Signed, Kind/Docs, no changelog

#2229 Represent or-patterns as a list in the AST
  lib/Ast.ml
  lib/Fmt_ast.ml
  lib/Normalize_extended_ast.ml
  lib/Sugar.ml
  lib/Sugar.mli
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/parser-extended/ast_helper.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed, no changelog

#2236 Make pcstr_self optional
  lib/Ast.ml
  lib/Fmt_ast.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
  vendor/parser-recovery/test/expect/structure/unclosed_class.ml.ref
  vendor/parser-recovery/test/expect/structure/unclosed_class5.ml.ref
  vendor/parser-recovery/test/expect/structure/unclosed_class6.ml.ref
  vendor/parser-recovery/test/expect/structure/unclosed_class7.ml.ref
  vendor/parser-recovery/test/expect/structure/unclosed_class8.ml.ref
  vendor/parser-recovery/test/expect/structure/unclosed_object.ml.ref
Labels: CLA Signed, no changelog

#2239 Add location to ptyp_alias
  lib/Fmt_ast.ml
  test/passing/tests/comments.ml
  test/passing/tests/comments.ml.ref
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed, no changelog

#2237 Add location to pcstr_record
  CHANGES.md
  lib/Ast.ml
  lib/Fmt_ast.ml
  test/passing/tests/record-loose.ml.ref
  test/passing/tests/record-tight_decl.ml.ref
  test/passing/tests/record.ml
  test/passing/tests/record.ml.ref
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed

#2238 Add locations to pval_prim strings
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/string.ml
  test/passing/tests/string.ml.ref
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
  vendor/parser-recovery/lib/recovery_parser.log
  vendor/parser-recovery/test/expect/structure/pr7847.ml.ref
Labels: CLA Signed

#2244 Add the exp_parens node in the AST
  lib/Ast.ml
  lib/Fmt_ast.ml
  vendor/parser-extended/ast_helper.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
Labels: CLA Signed, no changelog

#2234 Add optional package_type to pexp_pack
  CHANGES.md
  lib/Ast.ml
  lib/Fmt_ast.ml
  lib/Sugar.ml
  test/passing/tests/comments.ml
  test/passing/tests/comments.ml.ref
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/parser-extended/ast_helper.ml
  vendor/parser-extended/ast_helper.mli
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/parser.mly
  vendor/parser-extended/parsetree.mli
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed
