Repository ocaml-ppx/ocamlformat, pull requests merged in 2023-03, with the labels that each got.

#2259 Janestreet profile: Fix indentation of functions passed as labelled argument
  CHANGES.md
  lib/Fmt_ast.ml
  lib/Params.ml
  lib/Params.mli
  test/passing/tests/js_source.ml
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
Labels: CLA Signed

#2260 Refactor: Use Stdlib instead of Base.Caml
  bench/bench.ml
  bin/ocamlformat-rpc/main.ml
  bin/ocamlformat/main.ml
  lib/Ast.ml
  lib/Cmts.ml
  lib/Cmts.mli
  lib/Fmt.ml
  lib/Fmt.mli
  lib/Fmt_ast.ml
  lib/Fmt_odoc.ml
  lib/Literal_lexer.mll
  lib/Params.ml
  lib/Params.mli
  lib/Toplevel_lexer.mll
  lib/Translation_unit.ml
  lib/bin_conf/File_system.ml
  test/unit/test_fmt.ml
  test/unit/test_literal_lexer.ml
  test/unit/test_unit.ml
  vendor/ocamlformat-stdlib/fpath_ext.ml
  vendor/ocamlformat-stdlib/ocamlformat_stdlib.ml
  vendor/ocamlformat-stdlib/ocamlformat_stdlib.mli
  vendor/ocamlformat-stdlib/warning.ml
Labels: CLA Signed, no changelog

#2263 Fix dune files for opam-repo checks
  dune-project
  ocamlformat.opam
  test/unit/dune
  vendor/parser-recovery/lib/dune
Labels: CLA Signed, no changelog

#2272 Fix non-stabilizing comments attached to private/virtual/mutable keywords
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/comments.ml
  test/passing/tests/comments.ml.ref
Labels: Priority/High :fire:

#2284 Janestreet: Indent extension payload
  CHANGES.md
  lib/Conf.ml
  test/passing/tests/js_source.ml.ref
Labels: JaneStreet, Priority/High :fire:

#2289 JaneStreet profile: add extra parens around pattern-matching with type annotation
  CHANGES.md
  lib/Ast.ml
  lib/Sugar.ml
  test/passing/tests/js_source.ml
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
Labels: JaneStreet, Priority/High :fire:

#2303 tools/printast: Print extended AST
  lib/Extended_ast.ml
  lib/Extended_ast.mli
  lib/Std_ast.ml
  lib/Std_ast.mli
  lib/Syntax.ml
  lib/Syntax.mli
  lib/Translation_unit.ml
  lib/bin_conf/Bin_conf.ml
  tools/printast/README.md
  tools/printast/dune
  tools/printast/printast.ml
Labels: no changelog

#2307 Avoid breaking after the 'mutable' keyword
  CHANGES.md
  lib/Fmt_ast.ml
  test/passing/tests/comments_in_record.ml
  test/passing/tests/comments_in_record.ml.ref
Labels: no changelog

#2306 test_branch: Run ocp-indent for the Janestreet profile
  .github/workflows/build.yml
  test-extra/Makefile
  tools/test_branch.sh
Labels: no changelog

#2312 Treat *.ml{i} in Linguist as OCaml
  .gitattributes
Labels: no changelog

#2214 JaneStreet profile: improve indentation of function body when max-indent is used
  CHANGES.md
  lib/Cmts.ml
  lib/Fmt_ast.ml
  lib/Loc_tree.ml
  test/passing/tests/js_source.ml
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
  test/passing/tests/max_indent.ml
  vendor/diff-parsers-ext-parsewyc.patch
  vendor/parser-extended/ast_mapper.ml
  vendor/parser-extended/ast_mapper.mli
  vendor/parser-extended/asttypes.mli
  vendor/parser-extended/parser.mly
  vendor/parser-extended/printast.ml
  vendor/parser-recovery/lib/parser.mly
Labels: CLA Signed, Priority/High :fire:

#2319 doc: explain option enable-outside-detected-project
  doc/editor_setup.mld
Labels: Kind/docs, no changelog

#2261 JaneStreet profile: treat comments as doc-comments
  CHANGES.md
  lib/Cmts.ml
  lib/Conf.ml
  lib/Conf_t.ml
  lib/Conf_t.mli
  lib/Fmt_ast.ml
  lib/Fmt_odoc.ml
  lib/Fmt_odoc.mli
  lib/Normalize_extended_ast.ml
  lib/Normalize_std_ast.ml
  test/passing/tests/doc_comments-no-wrap.mli.err
  test/passing/tests/doc_comments-no-wrap.mli.ref
  test/passing/tests/doc_comments.mli.err
  test/passing/tests/doc_comments.mli.ref
  test/passing/tests/js_sig.mli.err
  test/passing/tests/js_sig.mli.ref
  test/passing/tests/js_source.ml
  test/passing/tests/js_source.ml.err
  test/passing/tests/js_source.ml.ocp
  test/passing/tests/js_source.ml.ref
Labels: CLA Signed, JaneStreet
